### ISSUE TITLE
Troubleshoot as an unauthenticated user

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#103]
Currently, our troubleshooting mode is for a single logged in instance (See #95), but many plugins and possibly themes, have special behaviors for anonymous users as well (including core).

Introducing a new feature to health check that simulates an anonymous session on the front end at will may be beneficial here.

**Comment by PeterBooker** [comment]
I am going to explore this and see how feasible/complex it is to do this through an iframe, much like how the customizer works. Otto42 pointed out that it could be done by setting a get parameter, which when detected triggers removing the auth cookie which would essentially render the session unauthenticated.

It feels like it might be over engineering something simple, but I think it would be a great experience for the user and could potentially be extended to cover different levels of permissions.

I will post back here once I have something worth sharing and/or have decided it is a dead end.

**Comment by Clorith** [comment]
The [User Switching plugin](https://wordpress.org/plugins/user-switching/) does this beautifully, it allows you to also do the troubleshooting as another user, or as a signed out one, it just works, so let's not re-invent the wheel here, and instead leverage other community resources.

**Comment by Clorith** [comment]
Going to close out this issue, maybe something built in will become part of the revamped Troubleshooting Mode in the future, but this isn't a given, but for now, this resolves the current implementation needs and leverages existing toolig.
