### ISSUE TITLE
Wrong version part for MariaDB

### ISSUE THREAD

**Issue by ssnepenthe** [WordPress/health-check#11]
Currently it is showing my MariaDB server version as "MariaDB" instead of "5.5.54".

https://github.com/WordPress/health-check/blob/55c2b2691ed8be1793e3a13a80420cee6b96965a/pages/health-check.php#L23-L29

Version string should be a format like "10.0.3-MariaDB-1~precise-log" (https://mariadb.com/kb/en/library/version/).

For example, on VVV I am seeing "5.5.54-MariaDB-1ubuntu0.14.04.1".

So the actual version string should come from `$version_parts[0]` instead of `$version_parts[1]`.

**Comment by ssnepenthe** [comment]
@Clorith for future reference, do you prefer small changes like this as issues or pull requests?

**Comment by Clorith** [comment]
Whichever one you are comfortable with, if you wish to do a RP you are more than welcome to 👍

**Comment by Clorith** [comment]
We may need a bit more logic here, as for some installs, the current format is correct to extract the version number.

**Comment by ssnepenthe** [comment]
Interesting... I just checked a trellis server which is running mariadb 10.0.29 and I get "5.5.5-10.0.29-MariaDB-0ubuntu0.16.04.1" which means the current logic does work as expected.

I wonder if the "5.5.5" prefix is added to determine mysql compatibility for mariadb 10? [This comment](http://php.net/manual/en/mysqli.get-server-info.php#118822) suggests that it is limited to windows environments, but I am on ubuntu.

[Maybe a `SELECT VERSION()` query would work better than `mysqli_get_server_info()`?](https://mariadb.org/explanation-on-mariadb-10-0/)

That accurately gives "10.0.29-MariaDB-0ubuntu0.16.04.1" on trellis and "5.5.54-MariaDB-1ubuntu0.14.04.1" on VVV.

**Comment by Clorith** [comment]
Good call on the use of `SELECT VERSION()`, went with it as the best approach, it also gets the right values for MySQL so we don't need them to behave differently.
