### ISSUE TITLE
Extending certain tabs

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#117]
Introduce actions/filters to extend other tabs than just the debug information.

**Comment by jocastaneda** [comment]
I gave it a quick pass and was thinking of something like: https://gist.github.com/jocastaneda/8eea236ec2ab1e6182057d78c611cd7e

**Comment by Clorith** [comment]
I like the thought, but I'm worried some features may be filtered away (think "our plugin/theme had issues with compatibility issues reported previously,just filter away that feature so we stop getting those reports" as an extreme scenario).

What if we kept the pages available as static, but instead introduced a filter on for example the Tools page specifically so that it's possible to add your own sections there as a starter, and see where it takes us?

**Comment by Clorith** [comment]
I did just notice that there already exists a filter for this in the tabs section, I've just committed a new doc-block to go along with it, 270014b2dec32f8b34ef478c166aea46170b41c6, that hopefully helps with usability (we do also use it internally in the plugin to populate this page for flexibility and to provide an example of its use). Not sure if we should do more here in the first iteration or see how this fares?

**Comment by jocastaneda** [comment]
Yeah, I saw that one too.

I say hold off for now

**Comment by Clorith** [comment]
All right, I'll close this for now and it can be re-opened later if we see the need for more extensibility.
