### ISSUE TITLE
Add a snappy tagline

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#132]
The plugin card can show a plugins tagline to better relay what the purpose of a plugin is, and if one isn't defined it will just take an excerpt of the plugin description it self, which isn't ideal and gets cut off.

![image](https://user-images.githubusercontent.com/468735/41816709-33334e08-778c-11e8-9b48-cf05fd9f743d.png)

We don't have one.

We should come up with a simple sentence that describes the plugin and how it can help users, or at least make them interested in reading the description to learn more.

We have 150 characters (no markup!) to work with, what could we make out of this?

**Comment by PeterBooker** [comment]
I tried a few ideas and my best attempt is "Health Check identifies common problems, and helps you troubleshoot plugin and theme conflicts.", which looks like this:
![health-check](https://user-images.githubusercontent.com/1855507/46320149-e32e4880-c5d4-11e8-8669-8b2795735aea.png)

**Comment by Clorith** [comment]
I think we can work with that, simple and clean, care to throw up a PR?
