### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [WordPress/health-check#142]
Hello @Clorith 

I want to contributo to health check and i designed a logo for it. What do you think? Also, Is there anything else you want?

![hcheck](https://user-images.githubusercontent.com/36298335/41938896-0a017a74-799d-11e8-917e-2263e14e4cd8.jpg)

**Comment by Clorith** [comment]
Hiya,

We've already got both a logo and banner for the plugin at this time (although I did notice we've not got them here on GitHub, so we should probably fix that), the current logo and banner can be seen at https://wordpress.org/plugins/health-check/ and we're currently quite happy to continue using those as they fit in well with other WordPress project logos.

We do always welcome contributions though, perhaps you have input for some of the other open items, many of them could benefit from a design/ux point of view and input on best practices and good flows to make sure features and enhancements provide a good experience for users.

**Comment by reallinfo** [comment]
Oh, okey. I understand. Thanks for comment.
