### ISSUE TITLE
Thanslation question: Is there a glitch on the "The Must User Plugin" string?

### ISSUE THREAD

**Issue by vitormadeira** [WordPress/health-check#15]
Hi. Is this string correct?
I'm trying to translate into Portuguese, but I wonder if the original string should be "The Must **Use** Plugin" instead?
Thank you.

--- ref. ---
Permalink: https://translate.wordpress.org/projects/wp-plugins/health-check/dev/pt/default?filters%5Boriginal_id%5D=5133412
References: pages/debug-data.php:180

**Comment by tobifjellner** [comment]
I think this was reported in issue #12 and corrected in https://github.com/WordPress/health-check/commit/bf5d921695798b4e2b29fb6d9d02ef4c364ce19f

**Comment by vitormadeira** [comment]
Great!
So now my that leaves me to a new question: Should I translated it right away with no 'fears' or will the translated string be vanished when the correct gets pushed on the repo?

**Comment by tobifjellner** [comment]
If you translate it correctly, then at least those using your translation will get the right meaning.
And when the source string is updated, then there is some chance that your previous translation will still be there, just marked as fuzzy. In that case, you’d just need to approve it.

**Comment by Clorith** [comment]
Hi,

This should indeed be fixed, there was some slowdown in translations on WordPress.org that should be corrected now, thank you for the heads up!
