### ISSUE TITLE
Add Permalinks check and web server brand

### ISSUE THREAD

**Issue by knutsp** [WordPress/health-check#171]
1. Display Apache/LiteSpeed/nginx or whatever returned
2. Check if URL rewrite is supported
3. If Plain is used and rewrite supported, suggest changing to pretty

**Comment by Clorith** [comment]
Displaying the httpd used sounds like a great idea.

As for suggesting pretty permalinks, we've defaulted to pretty ones for a few years now. Anyone still not using them are more likely than not to have made that decision on their own so I'd rather not step into that area, does that make sense?

**Comment by jocastaneda** [comment]
> Anyone still not using them are more likely than not to have made that decision on their own

True.

I'm totally in favor of adding Apache/LiteSpeed/nginx

**Comment by Clorith** [comment]
Milestoning the server daemon for 1.3, as I think that information may prove useful in many scenarios.
