### ISSUE TITLE
Add htaccess viewer to the Tools section

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#178]
We're testing to see if the `.htaccess` file has been modified outside of WordPress, but what if it has, the user may not be comfortable looking around in the file structure.

Let's add a viewer to the tools section for displaying the content of the file for them, which also makes it easier for them to copy and show it if needed.

We could probably add a copy-button to this area as well, like we do for the debug information field, so let's make that function a bit more re-usable while we're at it.

**Comment by jocastaneda** [comment]
Started work on this via this branch: https://github.com/jocastaneda/health-check/tree/178-htaccess-viewer

So far I have it only locally but this is what it currently looks like:

![htaccess](https://user-images.githubusercontent.com/1500554/44543462-72863900-a6c4-11e8-94a6-d274efd3fc30.PNG)

I think we may need to change the wording as well on [the line](https://github.com/WordPress/health-check/blob/master/src/includes/class-health-check-debug-data.php#L457) that shows the message.

**Comment by Clorith** [comment]
Looking good, yeah I agree we may want to make the heading line a bit more descriptive, perhaps chuck in an explanation of what it is before displaying the content of it?
