### ISSUE TITLE
Installed and active plugins number is incorrect

### ISSUE THREAD

**Issue by javorszky** [WordPress/health-check#179]
Discrepancy between what the plugin thinks is active and what plugins are actually active. See screenshots.

### Screenshots

What WordPress thinks about the plugins installed:

<img width="770" alt="screen shot 2018-08-18 at 12 10 47" src="https://user-images.githubusercontent.com/1196299/44298711-d339fe00-a2df-11e8-98bb-4c16d24acf18.png">

What the Health Check plugin thinks about the plugins installed:

<img width="1101" alt="screen shot 2018-08-18 at 12 11 57" src="https://user-images.githubusercontent.com/1196299/44298719-f1076300-a2df-11e8-823d-c33664880c1f.png">

Active plugins:

<img width="1203" alt="screen shot 2018-08-18 at 12 13 03" src="https://user-images.githubusercontent.com/1196299/44298729-201dd480-a2e0-11e8-9aec-431270ba7ba8.png">

The `Gabor's Debug Thingies` only contain two function definitions that I use for custom debugging, they are not hooked into any actions / filters. Other than that, all other plugins are standard.

**Comment by Clorith** [comment]
Is this all while not in Troubleshooting Mode?

**Comment by javorszky** [comment]
I don't know what troubleshooting mode is... so uh... I guess not?

**Comment by Clorith** [comment]
Awesome, just pushed an update to master with the changes, thanks for the heads up!
