### ISSUE TITLE
Wrong link to plugin home

### ISSUE THREAD

**Issue by knutsp** [WordPress/health-check#183]
### Feature request/bug description

http://wordpress.org/plugins/health-check/  should be https://wordpress.org/health-check/

**Comment by Zodiac1978** [comment]
@knutsp Where do you saw the wrong link? Here? https://github.com/WordPress/health-check/blob/56424e8680b6f5c76f478e84bed9dca48157d4c8/src/health-check.php#L8-L13

**Comment by knutsp** [comment]
Yes
