### ISSUE TITLE
Untranslated button in Loopback test

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/health-check#190]
### Feature request/bug description

The (probably dynamically generated) button "Test without plugins", which is shown if initial loopback times out, isn't translated.

### Screenshot
![2018-10-05](https://user-images.githubusercontent.com/24384895/46528085-2ddce880-c893-11e8-968c-d2d62f163441.png)

### Idea
I didn't find where in the code this button is generated. But if it currently is generated "on-the-fly" by script, then perhaps a better solution is to include the button in the static code, hide it with CSS, and have the script change its visiblity?

**Comment by PeterBooker** [comment]
This seemed like an easy/quick fix as the button label is generated in PHP, so I went ahead and made a PR.
