### ISSUE TITLE
Add 32/64-Bit mode info for PHP version

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#2]
https://github.com/WordPress/health-check/blob/master/pages/debug-data.php#L261

**Comment by Clorith** [comment]
Checked the PR, for *nix systems this is fine, but Windows systems limit integer values to 32bit no matter what, so it's not a reliable way to run detection on those platforms.

Adding a note to this if windows is detected as the OS would help I think, something like 

> You appear to be using a Windows based server, the reported PHP architecture may not be correct due to limitations of your operating system

(I am not good with words, so go with your gut here :) )

As a reference `if ( 'WIN' === strtoupper( substr( PHP_OS, 0, 3 ) ) )` is what core uses t ocheck for the existence of a Windows server

**Comment by Zodiac1978** [comment]
> Windows systems limit integer values to 32bit no matter what

Does this mean, they are always reporting a 32 bit mode? If that's true, then why it is a problem? Or do they report 32 and 64 bit, but still not allowing 64 bit values?

BTW here is a real issue with 32 bit vs. 64 bit from the support forums:
https://wordpress.org/support/topic/this-event-has-not-been-published-yet-again/

**Comment by Clorith** [comment]
Regardless of it being 32 or 64bit, they don't support 64bit values, so even if their PHP is 64bit, it won't work (the check in the PR will report that PHP ius running in 32bit mode no matter what of course, but so long as we know the value could be false we should make a note of it)

**Comment by Zodiac1978** [comment]
We could change the wording to something like "supports 64 bit values" (maybe in a new line?)

**Comment by Clorith** [comment]
Sounds good to me, make it so 👍

**Comment by Clorith** [comment]
The check is only introduced on the debug screen, on the generic health check page we're more concerned with versions than architecture :)
