### ISSUE TITLE
Add onboarding after actiavtion

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#206]
Currently, after activating a plugin, you are brought to the plugins screen.

This previously led to some confusion, where users would sometimes initiate Troubleshooting Mode and be lost as to what to do now. We alleviated this in 8860f75 with a new dashboard widget to inform them of what's going on.

A different thing that often comes up, is where to find things. To keep the plugin as unobtrusive as possible, it exists as a submenu item under `Dashboard`, which isn't always the simplest place to discover on your own.

Adding some kind of onboarding, perhaps we could ask the user what they'd like to do the first time after activation, with quick action buttons, for example:
- I want to check the health of my site
- I need data for my support request
- I'd like to troubleshoot a conflict

**Comment by kevinwhoffman** [comment]
As a new user, I had trouble finding it under `Dashboard > Health Check`. Given the nature of the plugin as a tool for debugging, I think it makes more sense under `Tools > Health Check`. In my experience, plugins that do not add their own menu items typically extend the `Tools` or `Settings` submenus.

It would also be helpful to indicate this location somewhere on the .org plugin page, either in the description, FAQ, or screenshots.

**Comment by Clorith** [comment]
Lets drop the modal thoughts, and instead do an admin notice style thing after first time activation, this gives a bit more flexibility and is easier to work with when looking at a11y needs.

We can then introduce the onboarding to this notice instead, cutting down on the backup warning to make it less frightening on activation for new users.

**Comment by hedgefield** [comment]
Sounds like a good idea. Some kind of landing page with the choices you mentioned might be nice for first-time users, to briefly explain how the plugin works and what you can do with it. Then we can also keep the other pages pretty lean and focused on the tools themselves.

Conceptually I agree that the Tools section would be a better home, but I also know I never look in there 😅When coming from the plugin installation it is hard to find, but the notice would solve that, and after that each time you open the admin you can see it under the Dashboard submenu, that might be a nice reminder. It feels more important and also more casual than a tool to me somehow.

**Comment by Clorith** [comment]
That was my thinking as well, it's a tool if you're troubleshooting, but if you are checking up on your site, it's an ongoing feature that feels more appropriate up there.

Related #226 is about adding an actual widget ot the dashboard so you get a quick overview of things when you log in.

**Comment by hedgefield** [comment]
Has it ever been considered to give it a top-level admin menu item? Site Health sounds like a good top-level item. Makes it easy to put a badge on it too when there are critical items.

So we also have the dashboard widget now, which is also a nice window into what's going on, but people won't see that after they activate. So a top-level item with badge could draw that attention, or perhaps an admin notice? With a CTA like "Take your first steps to a better site health by taking a look at these X issues". You wanna make sure people know the site status page is the place to be, and there's stuff that needs their attention. After that things should be relatively self-explanatory.

**Comment by Clorith** [comment]
Moved this to the 1.5.0 milestone, due to time constraints, but I think the admin notice is the way to go.

A top-level menu item is something I'd like to avoid, there's already enough clutter there, and replacing the Site Health from core under Tools feels much more natural at this point.

**Comment by Clorith** [comment]
It's been a while, Site Health is in core now, and folks know where to find it, and the plugin extends the core location as well.

I think it's safe to presume that for now, we don't have a discoverability issue like we used to, and close this ticket out. If more information comes back that indicates a need for it, we can always revisit at that time.
