### ISSUE TITLE
Feedback from Contributor Day (first users)

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#208]
### Feature request/bug description

This is no single bug report. These are some observations / feedback from the community from the Contributor Day at WordCamp Würzburg lately.

Feedback was:

-> Plugin name was confusing. People recommended something like "Support Tool(box)" or similar. "Health Check" was misleading for them.

---

![bildschirmfoto 2018-10-30 um 14 24 03](https://user-images.githubusercontent.com/870475/47721005-7ba8fe80-dc4f-11e8-8ebd-072792d8c386.png)

-> There is one information missing for Troubleshooting mode (although the text is already too long) - What needs to happen to enable all the plugins again? What happens if I disable the troubleshooting mode (will the current status remain?) How do I get the status from before?

---

![bildschirmfoto 2018-10-30 um 14 31 36](https://user-images.githubusercontent.com/870475/47721564-aba4d180-dc50-11e8-8151-1c878418671e.png)

This textblock (after enabling troubleshooting mode) needs a line break to make it more easy to skim. And maybe some bold text to get the **important** parts.

---

![bildschirmfoto 2018-10-30 um 14 31 56](https://user-images.githubusercontent.com/870475/47721681-f3c3f400-dc50-11e8-9e28-234b435320b6.png)

This "link" is in fact a toggle button. But we don't expect it to be a toggle. Maybe adding an arrow icon could help here. Additionally this link is not changing after show/hide. It always shows "Show all plugins". This seems to be a bug as I can see the markup for the "Show fewer plugins".

**Comment by Clorith** [comment]
Excellent feedback (and thank you, that's an awesome way to gather data)!

I agree with all of these points, I'd even go so far as to say we've improved the Troubleshooting Mode experience in such a way, we can probably remove the "warning" text with the yellow border line in it.

They're also fairly simple QoL improvements, so I'll chuck them on the 1.3.0 milestone!

**Comment by Clorith** [comment]
The only thing would be the name, although I can see how, depending on what you're using it for, it can seem right or wrong.

If you're at the site health table at WordCamps (we're making it a thing), then Health Check, makes sense. We did add the `& Troubleshooting` to help with explaining that it is for general purposes concerning both.

Using something like `Support toolbox` could then end up being even more confusing in some cases, as it then doesn't have a direct relation to the in-person things we're using it for... this point will obviously need much more discussions and time behind it, but the other points are quick fixes we'll definitely do right away.

**Comment by Zodiac1978** [comment]
Thanks for the fast reply @Clorith !

Changing the name is not easy. I do not expected to see this change, but as this was the feedback ... - maybe we can tackle this in the description a little bit more.

And one more thing: I wanted to show the 64 bit vs. 32 bit mode information and was confused as I didn't saw it. This is because we just show it if the 64 bit mode **is** available. But this should be the default and it is a _warning_ if this is not true. So we should invert this line:

https://github.com/WordPress/health-check/blob/ea689646fe93b14c99fa6692c06e563169242a93/src/includes/class-health-check-debug-data.php#L387

Something like:
`( 64 === PHP_INT_SIZE * 8 ? '' : __( '(Does not support 64bit values)', 'health-check' ) )`

or we show both modes:
`( 64 === PHP_INT_SIZE * 8 ? __( '(Supports 64bit values)', 'health-check' ) : '__( '(Does not support 64bit values)', 'health-check' )' )`

Thanks for considering!
