### ISSUE TITLE
Dashboard widget for site status

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#226]
The Site Status is handy, and holds states for things that may need looking into on a site (or that your site is going swimmingly!).

Would a dashboard widget on the first page make sense, so you don't have to go look it up on a secondary page make sense?

My thought is, as some tests need a few seconds to run, that it runs a cron task a couple times a day to populate the states, with a "refresh" action on the widget, so you always know if something has changed with your site.

I'd love some thoughts here on what this might look like, if it's a good idea and so forth.

**Comment by hedgefield** [comment]
I like this idea a lot, and it makes sense, you'd want a low-effort way to glance at the stats when you arrive in the admin. I can do some sketches when I finish with the status page, some ideas there could easily be duplicated into a simple actionable widget.

**Comment by Clorith** [comment]
Sounds great!

I'm thinking a quick and simple overview just to let you know there's things you should have a look at, we may not need a lot of action features right here, since that may end up overloading the dashboard instead (there's already so many plugins that add the whole kitchen sink there, I feel more compelled to ignore whatever's there in many cases).

**Comment by hedgefield** [comment]
Here's a simple design I was thinking of, combining the progress bar and a little bit of contextual copy to guide people to the status page.

<img width="583" alt="screen shot 2019-03-01 at 15 28 45" src="https://user-images.githubusercontent.com/6073772/53644392-c7d47180-3c36-11e9-9da4-37a764baa53c.png">

Added it to the prototype too: https://sketch.cloud/s/3P4LZ/ka9M15l/play

**Comment by Clorith** [comment]
Oh I do love this.

I 'm going to push the widget to v1.4 due to the current time constraints, but it's definitely something I want to introduce.

**Comment by hedgefield** [comment]
I've updated the mockup based on the new grading decision in https://github.com/WordPress/health-check/issues/342

<img width="601" alt="Screen Shot 2019-06-25 at 15 00 40" src="https://user-images.githubusercontent.com/6073772/60104295-73af4900-9761-11e9-8abf-f72b1b2a6671.png">

**Comment by Clorith** [comment]
I've implemented the widget from the screenshot above, the basis is the same data as used in the Site Health screen it self now (after #342).

And of course, the final line, pointing to the issues, is only there if there are issues to look at.

The text string above has three variations, depending on the issues;

A critical issue exists:
> Your site has critical issues that should be addressed as soon as possible to improve the performance or security of your website.

Only recommendations exist:
> Your site scores pretty well on the Health Check, but there are still some things you can do to improve the performance and security of your website.

No tests need addressing:
> Great job! Your site currently passes all site health checks.

This looks like a good first iteration to gauge reactions and such, it's a pretty noticeable sample group at this time, I'll close this ticket out now as implemented, if there's iterations down the line they should exist in separate issues.
