### ISSUE TITLE
Switch to eslint instead of jshint for linting JS files

### ISSUE THREAD

**Issue by dingo-d** [WordPress/health-check#229]
### Feature request/bug description

WordPress is already using `eslint` in their projects (I think Gutenberg is) and there already [exists](https://github.com/WordPress-Coding-Standards/eslint-config-wordpress) a dedicated eslint ruleset 

The plugin should use it instead of `jshint` 

To do:

- [ ] Add WordPress eslint config ruleset via `.eslintrc` or `.eslintrc.js` like [gutenberg is doing](https://github.com/WordPress/gutenberg/blob/master/.eslintrc.js)
- [ ] Modify gruntfile to use eslint to use it instead of jshint for JS file checking
- [ ] Add `eslint` to `package.json` along with the `eslint-config-wordpress`

### Reason why

`Eslint` is just better than `jshint`. It can be modified and/or extended more easily than `jshint`, plus every serious project in JS these days is using `eslint` 🙂

**Comment by Clorith** [comment]
eslint was introduced with 01966db0b1c1bd054845b986ac3fb3a54ba5cbd8
