### ISSUE TITLE
Undefined index: slug

### ISSUE THREAD

**Issue by webzunft** [WordPress/health-check#234]
### bug description

I am receiving this error

`Undefined index: slug in /wp-content/plugins/health-check/includes/class-health-check.php on line 306`

when going to the Plugins page. 

It appears 12 times in debug.log, while neither of installed, activated, disabled plugins is close to that number, so I have no idea where it is coming from.

It seems to be new, since I only saw it today and have the latest version running.

**Comment by Soean** [comment]
There is already a PR #235
