### ISSUE TITLE
Diff functionality no longer works on Windows

### ISSUE THREAD

**Issue by siliconforks** [WordPress/health-check#236]
### Feature request/bug description

As a result of one of the changes in version 1.2.4, clicking "View Diff" in the "File Integrity" tool no longer works if WordPress is hosted on a Windows system.  (The popup displays but just keeps showing the ajax loading animation forever.)

This is arguably a bug in the WordPress core `validate_file` file function; in fact there already exists a bug for this:

https://core.trac.wordpress.org/ticket/41736

(However, that bug has been sitting in the WordPress bug tracker for over a year without any signs of action being taken, so it is not clear if anything is ever going to be changed for that.)

**Comment by Clorith** [comment]
Hmmm, I agree this is something core should be fixing, I see the patch suggested there isn't ideal either though.

I'm wondering if we could work around this limitation, possibly by providing the path relative to `ABSPATH` when performing the file validation, and appending it afterwards when fetching the file?

**Comment by siliconforks** [comment]
Looking at the documentation in the Codex, it sounds like the `validate_file` function is intended to be used with relative paths; it says a return value of 0 means that "`$file` represents a valid relative path".

https://codex.wordpress.org/Function_Reference/validate_file

So, yes, maybe it would be best to provide the path relative to `ABSPATH` for validation.  That looks consistent with the way it is used in core WordPress, e.g., in the function `wp_edit_theme_plugin_file`:

```
$file = $args['file'];
if ( 0 !== validate_file( $file ) ) {
	return new WP_Error( 'bad_file' );
}
...
$real_file = WP_PLUGIN_DIR . '/' . $file;
```
