### ISSUE TITLE
Files in includes and modals directories should probably have ! defined( 'ABSPATH' ) check

### ISSUE THREAD

**Issue by siliconforks** [WordPress/health-check#237]
### Feature request/bug description

Files in the `pages` directory all have this check at the top of them:

```
if ( ! defined( 'ABSPATH' ) ) {
	die( 'We\'re sorry, but you can not directly access this file.' );
}
```

Is there any reason this is not done for the files in the `includes` and `modals` directories?  Right now, anyone can access these files directly (e.g., by visiting `http://example.com/wordpress/wp-content/plugins/health-check/modals/backup-warning.php`).  This is not really an issue in the present version since these files do not output anything important (e.g., if someone tries to access `backup-warning.php` directly, it will just generate an error as soon as it calls the `esc_html_e` function).  However, in the future a developer could inadvertently create a security issue by modifying one of these files to output sensitive information (e.g., suppose that a call to `phpinfo()` were added to one of these modals - then all the information output by that call would be viewable by anyone accessing the file directly).

**Comment by Clorith** [comment]
There's no particular reason not to include that check, it was just omitted because, as you said, there's no actual data in them.

I agree that upholding a good standard is ideal here to avoid them being forgotten when they may be needed in the future, so this should be remedied.
