### ISSUE TITLE
Plugin art

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#24]
The plugin currently has no banner or plugin icon that show up in WordPress and the plugin directory to help direct users to it.

This makes it appear unmaintained, compared to other plugins that show up for the same search terms, so let's see if we can get something together for this.

**Comment by tobifjellner** [comment]
Perhaps reuse the stethoscope from this free image: https://pixabay.com/en/heart-shape-stethoscope-health-care-1143648/ and combine it with a W-logo?

**Comment by Zodiac1978** [comment]
More flat icons which can be used (some requiring a backlink):
https://www.iconfinder.com/icons/1608853/stethoscope_icon#size=256
https://www.iconfinder.com/icons/353436/box_health_pulse_status_icon#size=256
https://www.iconfinder.com/icons/111046/health_medicine_icon#size=256
https://www.iconfinder.com/icons/753952/doctor_doctors_health_hospital_medical_medicine_icon#size=256

**Comment by Zodiac1978** [comment]
And more ideas for the header banner:
https://pixabay.com/en/medical-appointment-doctor-563427/
https://pixabay.com/en/electrocardiogram-blood-pressure-ekg-2858693/
https://pixabay.com/en/ekg-heartbeat-frequency-pulse-158177/

And more idea for the icon:
https://pixabay.com/en/stethoscope-icon-stethoscope-icon-2316460/

**Comment by Clorith** [comment]
I kinda like the idea of the pulse, we need to ensure any graphics used are GPL compatible, and backlinks are a bit hard to do for banners/icons unfortunately

**Comment by Zodiac1978** [comment]
All the pixabay images are CC0, so there are GPL compatible.

The only icon with no backlink requirement form the above is the stethoscope:
https://pixabay.com/en/stethoscope-icon-stethoscope-icon-2316460/

**Comment by Clorith** [comment]
What about the wrench from Dashicons using the default admin-ui colors? It's essentially more of a tool perhaps (just thinking out loud with some examples here).

![icon-128x128](https://user-images.githubusercontent.com/468735/36061855-21723632-0e61-11e8-8896-13df64d62ec3.png)
![icon-256x256](https://user-images.githubusercontent.com/468735/36061856-21f07ac4-0e61-11e8-900d-651905fc8ca4.png)
![banner-772x250](https://user-images.githubusercontent.com/468735/36061857-220ae5da-0e61-11e8-9818-24b28c6a2edc.png)
![banner-1544x500](https://user-images.githubusercontent.com/468735/36061858-225679dc-0e61-11e8-8567-249917ab9555.png)

It's very simplistic, which I'm a fan of, but feedback is always more than welcome

**Comment by tobifjellner** [comment]
Perhaps we could request that someone designs, say, a stetoscope, over at https://github.com/WordPress/dashicons/issues/new?labels=request

**Comment by tobifjellner** [comment]
![bw-stetho](https://user-images.githubusercontent.com/24384895/36063276-ef9c7860-0e7a-11e8-9750-a8610cd40977.png)

**Comment by tobifjellner** [comment]
![bw-stetho128](https://user-images.githubusercontent.com/24384895/36063426-ea9053c6-0e7c-11e8-9c12-e37ea3a2f4e5.png)
![bw-stetho256](https://user-images.githubusercontent.com/24384895/36063427-eab56c10-0e7c-11e8-9f43-4b00d9f09596.png)
Here's the same image cropped and sized for icon size (128 squared and 256 squared)

**Comment by tobifjellner** [comment]
As a banner, you can use this screenshot:
![banner-772x250](https://user-images.githubusercontent.com/24384895/36063548-9aa25466-0e7e-11e8-99b9-175b1b6cbd43.png)

**Comment by mrxkon** [comment]
![icon-128x128](https://user-images.githubusercontent.com/22611066/36174933-80a4e9e4-1116-11e8-93c4-4630078cfeca.png)
![icon-256x256](https://user-images.githubusercontent.com/22611066/36174937-84a9935a-1116-11e8-8f88-42634d7a8c68.png)
![banner-772x250](https://user-images.githubusercontent.com/22611066/36174939-86f4e164-1116-11e8-9016-dfec5ffdcbf1.png)
![banner-1544x500](https://user-images.githubusercontent.com/22611066/36174943-88dd0330-1116-11e8-8590-62cbf8071c6b.png)

The stethoscope pointed me to this idea instead of an actual stethoscope and oh well it's a heart... who doesn't like ❤️ ? + I had to use the wrench ofc ! 😈 

As for the banner, either something simple or I 👍 @tobifjellner idea ! Nothing more perfect than a screenshot :D

**Comment by Clorith** [comment]
I like this last iteration, except the banners. Remember that they need to make sense in RTL languages as well. I would also avoid text in the banner for that reason, and that text isn't translatable in there.

The little wrench shadow really does it justice, and the "heartfelt wrench" is nice :)

**Comment by mrxkon** [comment]
Hm, I'll try @tobifjellner idea of a simple screenshot that speaks on it's own ( while adding the icon on top as well ) or just remove the title and add some abstract pulse lines to just break all that blue a bit. I'll give it a shot later on today as well and post an update 😄 asap.

**Comment by tobifjellner** [comment]
Replacing the plugin name (which is anyway written next to the banner) with a pulse beat is a good idea.
And that one can also be mirrored for RTL.

**Comment by Clorith** [comment]
Aye, screenshots have the same limitation of including text, so let's try to avoid anything text-y :)

**Comment by mrxkon** [comment]
Would as simple as this make it ... perfect :D ?

![banner-1544x500](https://user-images.githubusercontent.com/22611066/36295720-fc09fe6c-12f1-11e8-9fd8-9ad8e2e3d779.png)
![banner-772x250](https://user-images.githubusercontent.com/22611066/36295721-fc2fa40a-12f1-11e8-8954-81ba735e7f11.png)

**Comment by Clorith** [comment]
Went with it, is live 👍
