### ISSUE TITLE
Backup reminder popup shows up again after being dismissed on some pages

### ISSUE THREAD

**Issue by siliconforks** [WordPress/health-check#240]
### Feature request/bug description

After installing the plugin for the first time, it shows a "Remember to keep backups" popup.  Clicking the "I understand" button closes the popup and should store a setting in the database so that the popup does not appear again; however, this does not work on all pages in the admin section.  On most pages the popup keeps showing up again.  If you go to the "Health Check" page and then close the popup, then it will successfully store the setting in the database and the popup will not be shown again (on any page).

It looks like this issue is caused by the new nonce in version 1.2.4.  On most pages, clicking the "I understand" button causes a JavaScript error:

```
ReferenceError: HealthCheck is not defined
```

It appears to be trying to access `HealthCheck.nonce.confirm_warning`, but the script that defines the `HealthCheck` object is not included on all pages.

**Comment by Clorith** [comment]
I'm putting in a quick-fix for this for version 1.2.5, as we're looking to remove that warning altogether moving forward (see also #206 )

**Comment by Clorith** [comment]
The backup warning modal has been removed starting with version 1.3.0, so this is no longer a concern.
