### ISSUE TITLE
Site Status page does not show async tests

### ISSUE THREAD

**Issue by siliconforks** [WordPress/health-check#244]
### Feature request/bug description

Looking in the method `Health_Check_Site_Status::get_tests`, there are two types of tests, `'direct'` and `'async'`.  The `'async'` tests ('Communication with WordPress.org', 'Background updates', and 'Loopback request') are not being displayed on the Site Status page.

Note that the async tests themselves are actually being performed - each async test causes an ajax request to the server which returns the test result - but the test output is placed in a hidden div on the page and never gets displayed to the user.

**Comment by Clorith** [comment]
That's right, it's part of some experimentation for the new UI/UX approach, pre-dating the now ongoing efforts in #227 (they didn't clean up perfectly in development, but with the ongoign efforts, it wasn't worth dedicating a lot of work into undoing this until we have a clear UI/UX plan), the live version does not hide these permanently.

**Comment by Clorith** [comment]
The tests are now cleaned up properly in the `develop` branch, so I'm closing this reference issue.
