### ISSUE TITLE
Improve debug data performance

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#249]
The Debug Data tab performs a lot of checks, one overloaded systems, or setups with low execution time limits, this may lead to a failure to load.

There are probably a few steps we could take to improve things here, the first ones that come to mind are the tests that rely on creating connections (loopbacks/WordPress.org communications for example), but there may be others, a benchmark here is probably not a bad idea.

**Comment by afercia** [comment]
Maximum execution time happens regularly for me. VVV install with "only" 50 plugins installed.

<img width="1267" alt="Screenshot 2019-03-16 at 13 37 42" src="https://user-images.githubusercontent.com/1682452/54475373-e28b1680-47f0-11e9-93a1-e8c7a7573bad.png">

I guess 30 seconds is the default on many hostings. I'd tend to think this is a concern important enough to be well considered before merging in core.

**Comment by Clorith** [comment]
Hmm, 880 is the install size generator, I'm not sure why that one is so slow for you, what PHP version are you testing with? For context, I ran it on an installation with 30 plugins and more than 5GB of uploads in ~3 seconds on a PHP 7.2 site, but the same did take nearly 12 seconds when tested with PHP 5.6, wondering if it really has that large of an impact, if that's the case it's a test that should, and can, be omitted for an initial core inclusion, and can be iterated on at a later stage.

**Comment by afercia** [comment]
VVV with PHP 7.2.15

I don't think it's related to uploads. Instead, I think it's related to the actual number of directories and files that get iterated. Some plugins have a `node_modules` directory with hundreds of nested directories and files.

I've removed all the plugins with a `node_modules_ directory reducing the content of my plugins directory to 120 MB with 4.749 files. Then, it runs in ~18 seconds. However, then the reported size is: "Plugins Directory | 0.00 B"

Regardless of `node_modules` directories, the uploads, themes, and plugins directories can potentially contain thousands of directories and files. I'd tend to think performance of `RecursiveDirectoryIterator` is a concern especially on cheap hostings.

**Comment by afercia** [comment]
> However, then the reported size is: "Plugins Directory | 0.00 B"

Update: Looks like this was caused by Glotpress development version: https://github.com/GlotPress/GlotPress-WP

There are a couple symlinks `.jscsrc` and `.jshintrc` that point to non existing files: these files will be created only on Travis.

**Comment by kevinwhoffman** [comment]
I wanted to add that `Health_Check_Debug_Data::get_installation_size()` was causing my site to hang.

## Local

I am running PHP 7.2.0 in Local by Flywheel. Activity Monitor shows that the CPU usage in Local immediately jumps to 99% when this method runs. I have to stop and restart the site to get the CPU usage to return to normal.

I only have a few plugins installed. I am developing a plugin with a large `node_modules` folder, so the overall size of `wp-content` is 347.8 MB.

## Production

On live sites in which the same plugin is present (without `node_modules`), the site health page takes about 10 seconds to load. So it does not freeze entirely like it does in local development, but it still takes an excessive amount of time to load.

## Workaround

When I comment out the following line, then the site health page loads immediately in both local and production environments.

https://github.com/WordPress/health-check/blob/e805010a157ba140e9a7cc17cb25609878c48012/src/includes/class-health-check-debug-data.php#L702

It took me quite a while to diagnose the problem, but by step-through debugging with Xdebug, I was able to see the execution stop once that method was called, and sure enough commenting it out fixed my issues.

**Comment by Clorith** [comment]
This should be resolved with #330, as we implemented a workaround for core that's now backported to the plugin.
