### ISSUE TITLE
[i18n] Separate Plugin Title from other strings

### ISSUE THREAD

**Issue by pedro-mendonca** [WordPress/health-check#25]
The Plugin Title "Health Check" string is the same as used in several titles used accross the plugin, as page, menu name, section tab. These should be translatable, keeping the plugin title independent and optionally not translatable.
Adding a context can solve this.

**Comment by tobifjellner** [comment]
:+1

**Comment by Clorith** [comment]
Good catch, definitely a good improvement for translators!

**Comment by Clorith** [comment]
Are there other areas that could benefit from enhancements like this (or other translation related enhancements)?

**Comment by pedro-mendonca** [comment]
Until now, I found only one more issue, related to the string "Return to table of contents".
It has the gettext function and textdomain, but can't get the translation from the .mo file.

**Comment by pedro-mendonca** [comment]
Ok found another one -> https://github.com/WordPress/health-check/pull/27

**Comment by Clorith** [comment]
Ahh yes, the translation not being included for the table of contents string, I've had another report of that as well, I've no idea what's causing it and haven't had a chance to look into it yet unfortunately.

Great work on the other strings though, thank you so much for grabbing that!

**Comment by pedro-mendonca** [comment]
As far as I've checked, it's not the only one, several strings from the same file are having the same problem.

**Comment by Clorith** [comment]
I've been testing the last issue with translation strings not being included as they should, and I've narrowed it down to the feature allowing you to grab the copy-and-paste field in English when your site is in a non-English language.

I'm going to create a separate issue for it to track it, and close this one as the string enhancements have all gone in so far.

**Comment by pedro-mendonca** [comment]
Great :)
