### ISSUE TITLE
Typo in PHP Extensions section

### ISSUE THREAD

**Issue by johnpgreen** [WordPress/health-check#252]
### Feature request/bug description

In the "PHP Extensions" section on the "Site Status" tab, modules that are not installed are indicated as not being "installer".

### Screenshots

![installed-not-installer](https://user-images.githubusercontent.com/4934384/52366966-f8026900-2a18-11e9-9d26-8d72cc7849b0.png)

**Comment by Soean** [comment]
There is already a PR #243

**Comment by Clorith** [comment]
This has been fixed in the `develop` branch, and will be included in version 1.3.0 of the plugin.
