### ISSUE TITLE
Typo in the PHP Extensions section of the Site Status tab

### ISSUE THREAD

**Issue by pbiron** [WordPress/health-check#255]
### Feature request/bug description

In the _PHP Extensions_ section of the _Site Status_ tab, if an optional extension is not enabled, the message is:

> The optional module, XXX, is not installer, or has been disabled.

Which should read:

> The optional module, XXX, is not installed, or has been disabled.

**Comment by Clorith** [comment]
Thank you for the heads up, we'll covered this in #243, or potentially with the string updates coming with #227.

Related #252
