### ISSUE TITLE
mcrypt reprorted missing or deactiavted on PHP 7.3

### ISSUE THREAD

**Issue by knutsp** [WordPress/health-check#257]
"The mcrypt extension is included in PHP 5.4 through PHP 7.1. It was removed from PHP 7.2 and moved to an unofficial PECL extension because the mcrypt library is no longer maintained."

Health Check describes mcrypt as required and reports that is it's missing. How is it?

**Comment by Clorith** [comment]
Much appreciated, this has been merged, and will be resolved in version 1.3.0 with some improved handling for bundled PHP extensions.

**Comment by bobbingwide** [comment]
Also applies to PHP 7.2
