### ISSUE TITLE
README of v1.2.5 has a missing space

### ISSUE THREAD

**Issue by szepeviktor** [WordPress/health-check#258]
See https://plugins.trac.wordpress.org/changeset?sfp_email=&sfph_mail=&reponame=&new=2014523%40health-check%2Ftrunk%2Freadme.txt&old=2011772%40health-check%2Ftrunk%2Freadme.txt&sfp_email=&sfph_mail=
after the version number.

Maybe that commit is missing from GitHub.

**Comment by Clorith** [comment]
Hiya,

Thank you for the heads up on that, it appears the readme wasn't updated here on Github, that's being fixed right now. The typo should be fixed on the plugins page as well shortly.
