### ISSUE TITLE
Copy to clipboard doesn't work

### ISSUE THREAD

**Issue by joyously** [WordPress/health-check#260]
I'm looking at the Info page on the version with accordion sections. I arrive at the page and click the Copy button, and when I paste I get whatever my previous copied thing was -- so the Copy button did nothing.

Do I have to select something first? That's not what the layout implies.

I'm on Ubuntu Studio 16.04 and tried it in Firefox 65 and Sea Monkey 2.49.4.

**Comment by Clorith** [comment]
This is a beta feature on the ui/ux branch that is awaiting accessibility input, I'll leave the ticket open in case others are testing that branch, but in general this isn't a issue with the live plugin.
