### ISSUE TITLE
combining recommendations?

### ISSUE THREAD

**Issue by joyously** [WordPress/health-check#261]
On the Status page, the Recommended improvements seem to be mashed together.
Since the accordions are all collapsed by default, it could give the wrong impression, and the user might not even see some things that are combined.
For instance:
* "**Inactive plugins should be removed**" is visible (and I had to type that because it wouldn't let me select it to copy it), but the description talks about having 11 plugins waiting to be updated, and then the thing about inactive plugins (which is really nonsense).
* "***Have a default theme available***" is visible, but the description says 3 themes waiting to be updated, xx inactive themes to remove, and then that I don't have a default theme (I have twentysixteen though).

It looks like the last thing becomes the title, instead of having them separate.

**Comment by Clorith** [comment]
This should be handled in #256
