### ISSUE TITLE
Troubleshooting Mode dashboard panel contrast and readability

### ISSUE THREAD

**Issue by afercia** [WordPress/health-check#273]
### Feature request/bug description

The Troubleshooting Mode panel in the dashboard has room for some accessibility and readability improvements:
- some text has a too low color contrast
- some lines of text are too long for optimal readability: I'd suggest to consider to introduces a max-width to make the lines of text not exceed 80-100 characters

### Screenshots

<img width="1279" alt="screenshot 2019-02-24 at 15 47 40" src="https://user-images.githubusercontent.com/1682452/53300799-d3492680-384b-11e9-9d09-36165f18ee48.png">

**Comment by Clorith** [comment]
Cutting the text length sounds reasonable here, I have a tendency to get carried away when explaining.

As for contrasts, is it only the `There are no notices to show.` string in the middle of the screenshot that is too low? I see the longer description is a lighter color but not as light.

**Comment by hedgefield** [comment]
The problem with the text is not per se the length of the sentences _word-wise_, but the width of the lines on the screen. Long sentences are okay as long as there are no more than ~16 words on one line. So I'd say capping the width of the paragraph to something like 640px will fix that.

As for the contrast, it's definitely the notices text that's too light yeah, but the main copy is also on the edge of being okay. I'd recommend to just make all the text as dark as the headings here, especially the explanation bit, there's no real cause to have it lighter than the default WP body text.

**Comment by Clorith** [comment]
For the record, the main text uses core's own class for the welcome box, I'll amend it for our use, but that's possibly something we'll want to look at for core as well concerning style for `.welcome-panel p`.

**Comment by hedgefield** [comment]
Ahh fair enough.

**Comment by afercia** [comment]
Yeah noticed it. I'd tend to think the core CSS class for the welcome box is tailored for that specific usage (bigger text, lighter grey) and maybe health check shouldn't use it.

**Comment by Clorith** [comment]
Sounds good! Swapping it all to use the default body color of the admin (what the plugin and themes lists in the box use already)

**Comment by Clorith** [comment]
I'm closing this out now then, as the contrasts were fixed in #280.

I've addressed the line lengths in the continuation of the design implementation 👍
