### ISSUE TITLE
Headings hierarchy for status page

### ISSUE THREAD

**Issue by joedolson** [WordPress/health-check#274]
### Feature request/bug description

Each accordion button is a heading element. Accordion items are headed by H2, but structurally they're descendants of the preceding `h3` headings, e.g. "n critical issues". This would make them `h4` elements

### Screenshots

Hierarchy:

![image](https://user-images.githubusercontent.com/1686451/53304492-92491600-383b-11e9-8033-746dec187b1d.png)

**Comment by Clorith** [comment]
Fixed in #277, also fixes the headings on the *Info* and *Tools* pages which had the same structural issue with the declared aria levels.
