### ISSUE TITLE
Image-only information in status

### ISSUE THREAD

**Issue by joedolson** [WordPress/health-check#275]
### Feature request/bug description

The distinction between types of issues raised (e.g., warning or error) is conveyed only by an image. This information is not available to screen readers. 

### Screenshots

Source code:

![image](https://user-images.githubusercontent.com/1686451/53304522-097eaa00-383c-11e9-8416-9a58bedf68c1.png)

Visual:

![image](https://user-images.githubusercontent.com/1686451/53304528-1ac7b680-383c-11e9-9fa7-cc60be635380.png)

**Comment by Clorith** [comment]
Absolutely, see also #267 which mentions this for the Tools section as well.

**Comment by Clorith** [comment]
Fixed in #278
