### ISSUE TITLE
Consider lightening list styling

### ISSUE THREAD

**Issue by melchoyce** [WordPress/health-check#281]
### Feature request/bug description

The strong shadow behind the lists make it feel very heavy, especially since the list and background are white-on-white. What if the lists didn't have outside borders or shadows?

### Screenshots

**Before**:

![image](https://user-images.githubusercontent.com/2846578/53515593-5ced3400-3a98-11e9-9ae1-aa424f329461.png)

**After**:

![image](https://user-images.githubusercontent.com/2846578/53515714-ab023780-3a98-11e9-9d50-71035b7e4312.png)

**Comment by hedgefield** [comment]
😄 that's actually how I had them before, but I got some feedback saying I should try them in the native Gutenberg collapsibles styling, since we also use that on the other pages. But I did always feel like the list of issues is of 'lighter weight' than the collapsible sections with their tables of info. You think it's worth introducing this stylistic element to the Gut design language here?

**Comment by melchoyce** [comment]
The Gutenberg collapsibles don't have shadows, though, because they're contained full-width within the light grey sidebar. Since this page doesn't have that context, I think not having shadows or borders along the edges feels more like Gutenberg 🤷‍♀️

**Comment by karmatosed** [comment]
This is great iteration @melchoyce. I would second that not having shadowing really makes it more like the Gutenberg interface. It's tempting to add in but if you look at principals like elevation, there isn't really any here to shadow.

**Comment by Clorith** [comment]
I've grown quite accustomed to the border 😂 (it does help containing the content when it's, as you mentioned, white on white) I totally get what you mean by the shadow though.

Here's the same view, but with the shadows dropped:
![image](https://user-images.githubusercontent.com/468735/53526013-69e34500-3ae3-11e9-80ed-fc0ec3d979c1.png)

It does have a border radius here, it feels a little less "poky" this way, but I'm happy to go with removing that as well if that's the preferred approach 👍

**Comment by Clorith** [comment]
After looking it over a bit, I'm removing the border radius as well, to be in line with all other core elements (and also it looked like there was a rendering gap when there's no shadow behind :) ).

**Comment by hedgefield** [comment]
Looks good to me, I've updated the prototype with this styling https://sketch.cloud/s/3P4LZ/WKrlQxn/play
