### ISSUE TITLE
Line height feels tight

### ISSUE THREAD

**Issue by melchoyce** [WordPress/health-check#282]
### Feature request/bug description

The line-height feels really tight. We generally use `line-height: 1.5` in core styles.

### Screenshots

**Currently**:

![image](https://user-images.githubusercontent.com/2846578/53515804-dbe26c80-3a98-11e9-9bc8-7dd4eac4c4d8.png)

**Comment by hedgefield** [comment]
I agree, we should use that here too. cc @Clorith

**Comment by Clorith** [comment]
Absolutely agree, just had a quick check and I see we did plan for that (perhaps subconsciously, as I noticed it's not documented anywhere but I did change it) 👍 

This is how it currently looks now:
![image](https://user-images.githubusercontent.com/468735/53525747-c5f99980-3ae2-11e9-8644-fe49499db81f.png)

Worth noting that it keeps the `line-height: 1.5`, but it also does `font-size: 1rem` as the text on the default `13px` was a bit hard to consume. This may be better if the text is condensed a little, but the slightly larger overall font felt much easier to read.
