### ISSUE TITLE
Troubleshooting dashboard widget styling

### ISSUE THREAD

**Issue by hedgefield** [WordPress/health-check#285]
Following #273 I went ahead and added the Troubleshooting dashboard widget to the mockups, and applied some extra styling to it to make it look smoooth.

https://sketch.cloud/s/3P4LZ/YGb1xl0/play

![dashboard](https://user-images.githubusercontent.com/6073772/53643354-1e8c7c00-3c34-11e9-8717-f1369700ac38.png)

**Comment by Clorith** [comment]
Oh, now that is just so much better than what I had thought!

I like that we're re-using the same accordion elements, keeps things consistent, great thought!

Do we perhaps have a plan if, as is often the case, there's 50 plugins, is setting a max height on the accordions here and allowing for a scroll area within a thought?

**Comment by hedgefield** [comment]
Ah scrolling could also be good. The length problem is indeed what made me think of the accordions, even having a list of 20 plugins would make this thing maaaassive otherwise. So maybe we start with all of the accordions collapsed and see how that feels? I don't want to saddle you with building a scroll area if it may not be necessary yet ha.

**Comment by Clorith** [comment]
Hah, sure, let's roll with this for now and judge it from there!
