### ISSUE TITLE
Too Many plugins and troubleshoot menu won't scroll

### ISSUE THREAD

**Issue by jbmanos** [WordPress/health-check#29]
I love this plugin!  This plugin is an answer to a long term problem I've had on some busy sites:  how can I test for plugin conflicts in the live environment without disrupting the public use of the site.  PERFECT!

However, I have too many plugins installed for troubleshooting mode menu.    For whatever reason, on my iMac, mac book, or iPad, the troubleshooting menu falls off the bottom of the screen and will not scroll.  This has the effect that, while in troubleshooting mode, I cannot enable plugins past “s” ( as the list is alphabetical) on my tallest screen and cannot get to the bottom of the list in the dropdown menu.

I like the way troubleshooting mode works otherwise -- it just seems like this aspect of it (the troubleshooting menu dropdown that allows one to select plugins for enable/disable) needs a way to accommodate a small screens and more plugins.  

Thanks!

**Comment by Clorith** [comment]
How many plugins do you currently have active on your site where the menu becomes too large?

I'm experimenting, and 20 seemed like an OK number to cut it off and provide a different alternative at, but curious to hear what number you were at when you discovered the issue.

**Comment by tobifjellner** [comment]
Well. Sorry for breaking in here. Someone _might_ be using this on a small mobile screen in horizontal position... So probably good to always have a back-up. Oh, and how does the top bar respond to touch-screen or screen readers, where you can't "hover"?

**Comment by jbmanos** [comment]
I find that after installing jet pack, security, site functionality and a page builder (with all the addon plugins) and form (with all their Addons), and a couple other necessary plugins (like the AMP plugin, glue for SEO), SEO, that 40-50 is a more realistic plugin count. And I don’t even count the caching plugin. 

Actually, if you add in any custom field/meta box plugins too, most sites that use the ordinary complement are going to be 40-50. 

20 is nice when you are a developer of your own functions, but even for me, I tend to break functionality into parts and have several based on type of functions.  

I’m just pointing out that it seems every plugin these days has two or more (free plus the Pro paid plugin) and many have shins (AMP needs AMP glue for SEO) etc.

**Comment by jbmanos** [comment]
Oh — I’m not sure what you mean by cutting off at 20.  

I know that the live site with 40 was not possible to use in troubleshooting. 

I didn’t try the other site that takes payments.  It has 60.

**Comment by Clorith** [comment]
Excellent, it sounds like 20 is a good number (if there are more than 20 plugins, it will use an alternate display that works better for sites with high plugin counts)

**Comment by jbmanos** [comment]
I just verified on a retina 13" macbook using the highest native resolution that I see 28 lines in the menu on that screen with the web page in safari sized to cover most of the screen -- 20 seems like a good cut-off there.   I don't know how a regular macbook would show, but I'm guessing that the height would be at least to the point where 20 hits.

It may be good, if possible, to permit the cut off to be set by the user in a setting on the troubleshooting panel.  Perhaps a checkbox that forces the alternate view.  This would accommodate the road warrior usage on mobile phones more easily by allowing them to force the alternate view even though they may not have more than twenty.  I've been that guy trying to fix a problem when all I have is a phone or ipad handy -- so it would be nice to be able to make it work in that context!

**Comment by Clorith** [comment]
What I'm thinking as the solution (what's currently in there in the commit referenced earlier in the ticket at least), is that if there are more than 20 items, it replaces the menu item with a link to the plugins page in wp-admin.

I've introduced the ability to enable/disable plugins from that screen, which will be much easier from most devices.

**Comment by jbmanos** [comment]
That works!!!   Heck, I’d like to be able to do that even if all the plugins showed up in the menu.   (I really do like the menu)

But, I could use one tab/window for the plugins and another for the front end view - and just refresh the front end view on (en|dis)abling a plugin.

**Comment by Clorith** [comment]
(You can do that even if everything shows in the menu :) )

**Comment by Clorith** [comment]
Closing out this ticket, as the solution is in trunk and will be included in the next release of the plugin.

**Comment by jbmanos** [comment]
Sweet!    Thanks, Marius!!!
