### ISSUE TITLE
Site status inbox zero

### ISSUE THREAD

**Issue by hedgefield** [WordPress/health-check#293]
When you solve all the issues in the site status tab, you want something nice and celebratory instead of an empty screen.

Here's a really basic take on it so there is at least _something_.

![site health check status inbox zero](https://user-images.githubusercontent.com/6073772/53817388-9e348680-3f65-11e9-82f0-eac4e1d08128.png)

Centered horizontally and vertically in the content area, with a dashicon for flair.

**Comment by Clorith** [comment]
Love it, there will be a "show passed tests" button still following it, for those that want to see what was checked and what the outcome was (to maintain a bit of consistency there), but that shouldn't be more than an added toggle button under the text, and still follow your plan here 👍

**Comment by Clorith** [comment]
Quick update, we'll replace the thumbs up with a check-mark tick thing.

Since the thumb up may have cultural significance depending on where you are from, and it's not always positive, we should avoid it.
