### ISSUE TITLE
"Return to table of contents" link is not showing the TOC

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#3]
After clicking the "Return to table of contents" link the user is directed to this anchor: #system-information-table-of-contents, but without using an offset, there is no TOC to see. The user has still to scroll up to see the navigation links.

**Comment by Clorith** [comment]
This is caused by the admin bar being there, if anyone has any good idea on how to circumvent this, I'm all ears, as I'm not entirely sure how we should approach it.

**Comment by Zodiac1978** [comment]
Quick&Dirty solution could be using just `#` instead of `#system-information-table-of-contents`

**Comment by Clorith** [comment]
That would bring you to the very top of the page, not an acceptable approach when considering a11y unfortunately.

**Comment by Zodiac1978** [comment]
Without JS I don't see any solutions.

**Comment by Clorith** [comment]
Adding some padding seems to do the trick, it unfortunately introduce some spacing between each section, it does help separate them and feels better to read, but adds some awkward spacing around the ToC it self.

![image](https://user-images.githubusercontent.com/468735/31577757-c831e7ce-b114-11e7-814c-f0c90980f6f2.png)

Adding a heading to the ToC make it seem less out of place, but there's still a fair amount of whitespace
![image](https://user-images.githubusercontent.com/468735/31577789-44cd688a-b115-11e7-8868-d6ee493ff28d.png)

(Definitely keeping the heading though, it helps with clarification)
