### ISSUE TITLE
Add mbstring and json as a PHP extensions to check for

### ISSUE THREAD

**Issue by knutsp** [WordPress/health-check#310]
### Enhancement

Both mbstring and json have polyfill functions to mimic the library in wp-includes/compat.php
A fully healthy installation should not have to use fallbacks or polyfills.

**Comment by Clorith** [comment]
The JSON extension has been bundled with PHP since 5.2.0, so this is a non-issue any more, the polyfill in core is merely there for backwards compatibility.

mbstring makes sense to add in though.

**Comment by knutsp** [comment]
json: Believed so until I found "json" as a tickable option for PHP 7.3 on CloudLinux/cPanel, saying "Allows work with text data interchange format with parser built on JSON_checker". This may be an alternative/fork or extended thing?

mbstring: Even for en_US as site charset I think

**Comment by Clorith** [comment]
That does look to be a custom module, yeah, so we won't be including that.

**Comment by Clorith** [comment]
I've implemented the `mbstring` and `json` checks in 529e3b3a7fb3b120ba306ca181ed89937dac8031

After some consideration, and more recent discussions in Slack about removing polyfills, it makes sense to perform the check. And as polyfills are generally there to ensure functionality we require, they've both been marked as required modules.
