### ISSUE TITLE
Check that object cache is not disabled

### ISSUE THREAD

**Issue by knutsp** [WordPress/health-check#311]
### Feature request

Situations from the wild/field over some years, in my experience:

1. Disabling object cache by filter
2. Plugin enables static object cache, but the server (memcache/redis/whatever) does not always respond immediately or simply doesn't work or is not started/installed at all. Not all cache plugins check that.
3. _Empty_ `object-cache.php` file left over from a bad plugin. Some add it as just a placeholder and may not be deleted upon uninstall.

All situations slow down WordPress tremendously, the admin area especially.

1 and 2 should in one way be covered by the debug feature of this health check plugin, but 3 is not. Most novices will just think they have too many posts, images, plugins, comments, a complicated theme, too cheap host and so on, since their site/admin is so embarrassingly slow.

**Comment by Clorith** [comment]
I'm moving this to the 1.5.0 milestone, but I would like to investigate this further.

Do you have any thoughts on how we could reliably check for points 1 and 2?

**Comment by knutsp** [comment]
I'm no cache expert, but could start by checking $_wp_using_ext_object_cache. The ideal goal is to check that object cache "works", but this not a performance or speed test. Could perhaps test that set + get cache immediately returns the value (no delay, not failing).

**Comment by Clorith** [comment]
The Site Health checks and debug information have been taken out of the Health Check plugin as of version 1.5.0 (with some backwards compatible layers for sites running WordPress versions earlier than 5.2), and any new issues relating to these areas should be opened in the [WordPress core trac](https://core.trac.wordpress.org/).

Noting that checks for cache solutions went into core recently, and will be included in WordPress 6.1
