### ISSUE TITLE
Button styling not consistent with core styling

### ISSUE THREAD

**Issue by afercia** [WordPress/health-check#314]
Not sure why the buttons font-size is bigger than the standard in core:

<img width="874" alt="Screenshot 2019-03-16 at 13 42 16" src="https://user-images.githubusercontent.com/1682452/54475419-807ee100-47f1-11e9-9870-ffea58a34d86.png">

If Health Check is going to be part of core, I'd say it should just use the core styles. No exceptions, consistency is important.

**Comment by Clorith** [comment]
Yes, the font size is slightly larger here, and for text in general (it's 1rem, translating to 16px, as opposed to the 13px core uses), this is done for readability.

For the plugin it self I'd like to experiment with it as screens get larger for desktops, and handheld devices also get higher resolutions the font size feels more readable.

I have no problem removing these style overrides from any core patch though 👍

**Comment by afercia** [comment]
I might understand a 16 pixels font size for normal text, though inconsistent with core. Ideally, these changes should be evaluated holistically. I'd tend to think having some admin pages with a default font size of 13 pixels and other pages with a default font size of 16 pixels is not ideal.

Re: buttons, they really don't look OK with a bigger font because the buttons size is crafted for a smaller font.

**Comment by Clorith** [comment]
I agree with your thoughts here.

We'll not include the font changes in the core patch, I'd still like to evaluate how they work out in general for the plugin by it self, as I've heard feedback on the fonts being too small in general, perhaps this is a good way to test the need for a larger core font size at a later date..?

**Comment by hedgefield** [comment]
If possible I'd like us to make a start on the font size matter right away - doesn't have to be via this project but as you say holistically. We've been tinkering with our product styling at Yoast, and anything that looks good in regular web context looks huge when put next to the small WordPress font. I'll raise it in the design meeting this week to test the waters.

**Comment by afercia** [comment]
FWIW: I'd agree the WordPress default font size is too small with today's screens 🙂 However, the point is Health Check should just look like a WordPress admin page.

**Comment by hedgefield** [comment]
Well, FWIW, these pages are styled like Gutenberg which is what no other admin page has done yet ;) but consistency in text and buttons is fine yes.

**Comment by Clorith** [comment]
Having re-visited this, the styling matches the core styles at this time, so I'll close out this ticket for now :)
