### ISSUE TITLE
Headings shouldn't use a serif font

### ISSUE THREAD

**Issue by afercia** [WordPress/health-check#315]
Not sure why the headings use a serif font:

<img width="892" alt="Screenshot 2019-03-16 at 13 45 51" src="https://user-images.githubusercontent.com/1682452/54475469-e8352c00-47f1-11e9-8188-ff13f89aed42.png">

This is unprecedented in core, where serif fonts are not used, and for good reasons.

If Health Check is going to be part of core, I'd say it should just use the core styles. No exceptions, consistency is important.

**Comment by Clorith** [comment]
I questioned this as well at first, but @hedgefield mentioned it is the heading font used by Gutenberg, giving a ping as he's likely the better person to answer this than I (the generic serif is if the Google font isn't loaded)

**Comment by afercia** [comment]
The heading font used by Gutenberg depends on the active theme.

**Comment by hedgefield** [comment]
I find the font adds a bit of flair to the page, but it works fine with the sans-serif font too, if that's better for a11y, go with that. 👍

**Comment by Clorith** [comment]
These screens now use WordPress core styling, and is sans-serif at this time :)
