### ISSUE TITLE
Unable to copy file to enable Troubleshooting Mode notice

### ISSUE THREAD

**Issue by grappler** [WordPress/health-check#316]
### Bug description
I installed Version 1.2.6 and tried to activate the "Troubleshooting Mode" but got the notice:
> We were unable to copy the plugin file required to enable the Troubleshooting Mode.

I have two issues. One I am not sure why the plugin file could not be copied. Secondly the notice seems to be wrapped in two notices.

### Screenshots
![image](https://user-images.githubusercontent.com/1785641/54488061-67cc0500-489d-11e9-86fa-2b3c59f6c36d.png)

**Comment by grappler** [comment]
I started looking at the notifications code but I was not able to come up with a good solution without making larger changes. I added some comments as inline comments to some code that I did not fully understand the reasoning for. The commit with this can be found: https://github.com/grappler/health-check/commit/3e942bd3763d83046168f5f658cd775bf5ba9948

**Comment by Clorith** [comment]
Closing this issue as the notice wrapping issue was resolved, and the copying issue should no longer be a problem without a notice after moving to use `$wp_filesystem` for handling file-manipulation.
