### ISSUE TITLE
Check that WordPress time zone is not set as fixed UTC offset

### ISSUE THREAD

**Issue by knutsp** [WordPress/health-check#317]
### Feature request

Using UTC offset will not switch automatically when DST is active. Even if many/most countries does not use DST, the list of nearest cites should be sufficient and regarded most healthy for a site, and could easyliy be detected bu this plugin.

Some sites in DST countries show a wrong time indication half of the year.

**Comment by Clorith** [comment]
I do like that, yes! The timezone setting can be confusing in that regard, especially on older site I find this to be more common to use the UTC offset over a city name (as many won't know it's a thing to pick a city).

Good call, adding it to the 1.4 milestone.

**Comment by Clorith** [comment]
Added in e5f5053813530ca4f6e767cff953a9c14b3d8c9f
