### ISSUE TITLE
Imagick or ImageMagick

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/health-check#32]
In the current strings, there are two mentions of Imagick and one of ImageMagick. I believe they are referring to the same thing and thus ought to be written in the same way?

**Comment by Clorith** [comment]
Actually, one is for the PHP library, the other is for the library on the server it self, they're spelled out differently in all documents online for some reason

**Comment by Clorith** [comment]
Closing, as they are actually two different things as intended.
