### ISSUE TITLE
cURL error 60: during REST API availability check

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/health-check#322]
At yesterday's WordPress Portsmouth Meetup a number of us ran health checks on our sites. 
I ran it in my local development environment. I have a self certified SSL certificate that enables me to access my sites using HTTPS, but I'm forever suffering from `cURL error 60: SSL certificate problem: unable to get local issuer certificate.` 
This problem raised it ugly head during the REST API availability check.

In most other situations, in order to continue, I have worked around this problem by hooking into `https_request_args` and setting `sslverify` to `false`.
The filter I normally use includes logic to determine if the request is being performed locally.

This problem also prevents the Loopback request from completing. 

### Workaround
Since this also fixes another problem
```
function oik_clone_http_request_args( $args, $url ) {
	$args['sslverify'] = false;
	return $args;
}
```

### Feature request/bug description

I wonder if there's anything that can be done to avoid displaying the failure message when the tests are being run in a local development environment. 

Ideally, I'd like to know how to configure my local development environment so that I don't get the problem in the first place. I'm sure there are many others who would like to know how to do this. 

Alternatively,  it would be nice if the request could be retried with sslverify false and an appropriately worded warning produced. 

I know that REST requests are working since the block editor works. 

### Screenshots

Is this a visual related ticket? If so, please include one or more screenshots to help us better understand what is happening.
![image](https://user-images.githubusercontent.com/2474435/54748421-85fd7200-4bc9-11e9-8c1c-402e4af6b5db.png)

**Comment by Clorith** [comment]
WordPress core will dictate the site health checks moving forward, and already has some checks for local installs in place at this time.

In light of this, I'm closing this ticket in favor of core, and if enhancements need to be made, those should now happen in core.
