### ISSUE TITLE
Some of the messages need further explanation

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/health-check#323]
### Feature request/bug description
What should a user do when the Health-Check plugin finds that there is something wrong with the site? 

In my development site I was getting a number of messages.
As I'm a developer I've been able to deal with some of them myself.
See #322 and https://github.com/bobbingwide/oik-bwtrace/issues/77

For both of these issues I needed to debug the problem to find the true explanation.

It would have been nice if each of the messages had 
- a ( separately documented) explanation that would 
- attempt to further explain the problem
- and how to resolve it.  

I would expect this to be part of the documentation that would be included in the Handbook. 
This documentation would be needed by Support as well as the User / Developer running the Health check.  

### Example
The folder `C:\apache\htdocs\wordpress` was detected as being under version control ( `.git` );

#### Problem explanation
If WordPress detects that the site's installation directory is under some form of version control then it will not apply any updates automatically. Not applying the updates can lead to vulnerabilities.

#### Problem resolution
Check if your site has any updates that need applying. If so, either apply the updates using your version control system or, if you did not expect the site to be managed by a version control system remove the version control files. 

- - - - - 

In the good old days this was documented in a messages and codes or problem determination guide.  Remember: You can't tell a user to RTFM if you have not yet performed the WTFM task.

**Comment by Clorith** [comment]
So, part of this is planned for version 1.3.0 of the plugin, where each test has an explanation of what this feature does and why it's important, and will, when possible, provide either steps on how to fix it your self, or links to documentation. See #256 for a big introduction of the mass amount of new strings we are introducing to help with this.

Would that be along the lines of what you were thinking of here?

**Comment by bobbingwide** [comment]
Thanks. I didn’t see #256.  
So what’s the other part that’s not planned?

**Comment by Vilasamuni** [comment]
I want to keep `.git` in the root of my WP install so I can track settings in `.htaccess` as well as custom themes and plugins, but I want to automatically install updates for WP core and non-custom themes and plugins. Is there a way to override this and say "I know what I'm doing, please enable auto updates even though  `.git` is present?

**Comment by Clorith** [comment]
The Site Health checks and debug information have been taken out of the Health Check plugin as of version 1.5.0 (with some backwards compatible layers for sites running WordPress versions earlier than 5.2), and any new issues relating to these areas should be opened in the [WordPress core trac](https://core.trac.wordpress.org/).

There is an active ticket for improving some of the acitonable items and descriptions of the checks at https://core.trac.wordpress.org/ticket/50389
