### ISSUE TITLE
String is not translatable

### ISSUE THREAD

**Issue by mobby2561** [WordPress/health-check#325]
The following string is not translatable:
 https://github.com/WordPress/health-check/blob/490e46553ddce11153af6500985a313fda077997/src/includes/class-health-check-debug-data.php#L322
And as WordPress Core uses _email_ instead of _e-mail_, the following string should be changed.
https://github.com/WordPress/health-check/blob/490e46553ddce11153af6500985a313fda077997/src/includes/class-health-check-mail-check.php#L105

**Comment by Clorith** [comment]
Thanks for the heads up on the core-approach to the terminology here.

As for the translation string, I see that's already been handled :)
