### ISSUE TITLE
Introduce Ignore Functionality

### ISSUE THREAD

**Issue by garrett-eclipse** [WordPress/health-check#326]
### Feature request/bug description

Coming from [core#46733](https://core.trac.wordpress.org/ticket/46733) am requesting the consideration of Ignore functionality on tests.

This would allow admins to dismiss issues they've already cognitively ignored. Tieing this functionality to user_meta would ensure admins couldn't 'hide' test results from other admins.

This functionality is to address the issues where utilizing the suppression filters are excessive and can be a disservice to the site health, as well as to reduce the noise on the page and allow relevant/updates tests to take precedence and stand out from others which may have been ignored due to them always being present.

This would follow on the lead of other plugins such as Wordfence which allows for not only an ignore but an always ignore. I feel just an ignore which could be dismissed by a change in the test results would serve best so new issues can re-asire on the important list.

The ignore list would also benefit from an 'unignore' in case of error or change in environment.

### Screenshots

Original screen of test an admin may choose to ignore;
https://core.trac.wordpress.org/attachment/ticket/46733/Screen%20Shot%202019-03-30%20at%2012.52.08%20AM.png

**Comment by Clorith** [comment]
After consideration (see core ticket), I don't think this is something we should do. The introduction of filters to results means plugins can hook in, check the results and conditionally ignore things on their own, which is a much cleaner solution which puts less focus inside Health Check it self.
