### ISSUE TITLE
Memory Limit and other values can be -1 which can be confusing

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#332]
### Feature request/bug description

Memory Limit and other values (like `max_input_time`) can be -1 which can be confusing for beginners. It means there is no limit (or the limit is set on a higher level in the server config).
https://www.php.net/manual/de/ini.core.php#ini.memory-limit

The company 1and1/Ionos has this "issue" and is a big player, at least in Germany.

Maybe we can add an explanation if the value is "-1", that this means the above.

**Comment by Clorith** [comment]
Did you hve some special area you were considering for this?

**Comment by Zodiac1978** [comment]
I've just experienced it for `memory limit` and `max_input_time`.

Another "problem" is memory limit showing bytes instead of megabytes (268435456 for example, which is 256 Mebibyte)

**Comment by Zodiac1978** [comment]
From https://www.php.net/manual/en/info.configuration.php#ini.max-input-time

> This sets the maximum time in seconds a script is allowed to parse input data, like POST and GET. Timing begins at the moment PHP is invoked at the server and ends when execution begins. The default setting is -1, which means that max_execution_time is used instead. Set to 0 to allow unlimited time.

**Comment by Zodiac1978** [comment]
> Another "problem" is memory limit showing bytes instead of MiB (268435456 for example, which is 256 Mebibyte)

Here is a first idea how to fix this:
https://gist.github.com/Zodiac1978/3205315bc772b95ec7c80c3e0b37bc20

**Comment by Zodiac1978** [comment]
@Clorith Did you have a look at my gist? Is this interesting for Health Check and should I prepare a PR for this?

**Comment by Zodiac1978** [comment]
@Clorith Any chance to have a look at my code?

**Comment by Zodiac1978** [comment]
Still interested in feedback about this, @Clorith

**Comment by Clorith** [comment]
Hiya, sorry this totally got lost in my pile here.

The debug screen isn't intended to explain data to the end user, it's a place to collect information, as it is presented in any config situation, for sharing with support individuals, or those with technical experience.

As such, I don't personally believe we should be manipulating that data in any way in the debug/information screens. The exception o this is the Site Health checks, which are aimed at any user, and should be presented there in a human readable format when possible.

**Comment by Zodiac1978** [comment]
It makes sense to not manipulate the data, because this could lead to false assumptions on the user side. But we could add at least some information what -1 means or add the MB version if bytes are provided.

Very often the system checks of themes and plugins get this wrong and users see something like this:
![Bildschirmfoto 2021-02-22 um 09 28 03](https://user-images.githubusercontent.com/870475/108682278-67f4c680-74f0-11eb-975b-7b10d1b3f6d8.png)

We should be better and educate the people or at least provide links where the user can find the explanation IMHO.

**Comment by Clorith** [comment]
I#m vary of sending users on a wild chase down the rabbit hole if we provide too much context or options/alternatives here. If a user is of the inquisitive type, they#ll already be familiar with looking up things and finding it out, otherwise we may accidentally send a user just looking around into a spiral of confusing technical documentation that they have no use for at all.

**Comment by Zodiac1978** [comment]
This does not make sense at all for me. If we do not give any further details what "-1" means or where the user gets this information *then* we will chase them down in a rabbit hole to find out what the "-1" means. Because it is not at all intuitive for non devs. 

If someone is not able to understand our simple explanation ("-1 means unlimited" or "-1 means the value from x is used") this screen wouldn't be accessed in the first place (or just for copy&paste).

The world is not divided in devs and users, there are juniors, hobbyists, self educated people and so on - and I think giving them explanations, educate them or help them with finding good resources is key here.

**Comment by Clorith** [comment]
The Site Health checks and debug information have been taken out of the Health Check plugin as of version 1.5.0 (with some backwards compatible layers for sites running WordPress versions earlier than 5.2), and any new issues relating to these areas should be opened in the [WordPress core trac](https://core.trac.wordpress.org/).

It looks like this might fit into the coverage of https://core.trac.wordpress.org/ticket/46945
