### ISSUE TITLE
Check and recommend intl extension

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#333]
### Feature request/bug description

This extension should be recommended IMHO. It is necessary to use the Normalizer function which would solve many problems with internationalization issues for special characters:
https://www.php.net/manual/en/intl.requirements.php

**Comment by fierevere** [comment]
_intl_ has hard dependency on _icu_ system libraries, which will consume over 30 Mb diskspace on smaller (VPS/embedded) systems. Each loaded library claims some memory and initialization time overhead.

Bigger distributions can link libicu to _libxml2_ library and therefore it can be loaded by _libxml2_ linked extensions, but this dependency is optional

**Comment by Zodiac1978** [comment]
@fierevere Thanks for the additional info! But what is your recommendation? I just want to know if the `normalize_normalize` function is available.
https://php.net/manual/de/normalizer.normalize.php

Thankfully I can easily add this myself (and have already a little plugin for this) but maybe this is something that is useful for all (in the future).

So do you recommend to not use `intl`, because it consumes too much space and memory?

**Comment by fierevere** [comment]
Its just a statement, not a recommendation to use or not to use.

WordPress can play with _remove_accents()_ https://developer.wordpress.org/reference/functions/remove_accents/ built-in function if needed. I belive it does same thing.

**Comment by Zodiac1978** [comment]
> I believe it does same thing.

Unfortunately it does not help here. See this ticket: https://core.trac.wordpress.org/ticket/35951

**Comment by Zodiac1978** [comment]
If someone wants to test for `intl` in Health Check, here is a small plugin solution:
https://gist.github.com/Zodiac1978/ce9db99becd3507ec8d8207c583e947b

**Comment by Zodiac1978** [comment]
There is a ongoing discussion in the hosting team about which extension is recommended/required. `intl` is mentioned three times:
https://make.wordpress.org/hosting/2019/06/11/php-requirements-check-in/#comment-73
https://make.wordpress.org/hosting/2019/06/11/php-requirements-check-in/#comment-75
https://make.wordpress.org/hosting/2019/06/11/php-requirements-check-in/#comment-79

Next step is outlined here https://make.wordpress.org/hosting/2019/07/27/hosting-meeting-notes-july-22-2019/

> @zodiac1978 requested an update on the PHP Extension recommendations. This is at the point where feedback needs to be compiled and shared. If you’d like to help put a post together, please leave a comment on this one!

**Comment by JasonTheAdams** [comment]
Chiming in here, this would be excellent for us at [GiveWP](https://givewp.com). We currently have to handle things like currency position, thousands separator, and so forth ourselves. It's tedious and prone to issues as it has increased complexity. Having the Intl library reliably would really clean this up and improve the overall user experience. 👍

**Comment by Zodiac1978** [comment]
@Clorith Is this the wrong place for such checks? Do I need to open a trac ticket instead? Is this the better approach?

**Comment by Clorith** [comment]
Recommendations about which PHP extensions are available should be created as Trac tickets yes, please :)

It should be noted that PHP extension recommendations are based off what the [Hosting Team](https://make.wordpress.org/hosting/) suggests, so passing it by them seems reasonable as well here.

**Comment by Clorith** [comment]
Closing as new, or modified, Site health Checks should now be created in WordPress core, and as such please make a ticket on the [Core Trac](https://core.trac.wordpress.org/)

**Comment by Zodiac1978** [comment]
Thanks for four reply @Clorith 

> It should be noted that PHP extension recommendations are based off what the Hosting Team suggests, so passing it by them seems reasonable as well here.

Yes, I have mentioned this in one of their meetings: https://make.wordpress.org/hosting/?s=%22intl+extension%22

The overall user feedback is positive but not much traction on the hosting side ...

**Comment by Zodiac1978** [comment]
Moved to: https://core.trac.wordpress.org/ticket/52654
