### ISSUE TITLE
Modify the grading indicator

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#342]
The grading indicator is a source of some controversy (see https://core.trac.wordpress.org/ticket/47046)

Let's either make it clear that this is just an indicator of how many tests are passing, or look at no longer devaluing for recommendations as well.

The current approach is that critical issues are weighted and remove from the overall value, recommendations just devalue at a normal 1:1 ratio, and good results are the only ones that push the needle forward (this is because it's a tests passed indicator, with some push for critical issues, more so than a grade).

**Comment by hedgefield** [comment]
I still like the weighted count, as critical issues _are_ more important than recommendations. The problem comes from people wanting to complete everything, so calling it 100% or passed tests probably won't make much difference, I'm thinking we should try making the grading less actionable. 

We could divide it into three tiers, like 'bad/OK/good'. It'll always say 'bad' if there are several open critical issues, and it can be 'good' even if there are still some open recommendations. How does that sound?

**Comment by Clorith** [comment]
Sounds good to me, so we'll keep the color indicator, but does the progress-style make sense now, or would the traffic-light format of a "dot" be more in-line if there's no text-fill?

We'll leave the weighting as it is and focus on the header element instead.

**Comment by hedgefield** [comment]
I can do a few mockups of the different options, a smaller filled indicator makes more sense probably than the progress ring then.

**Comment by hedgefield** [comment]
I dropped a few ideas into mockups, let me know what you think:

https://sketch.cloud/s/pLoZG

**Comment by Clorith** [comment]
I'm torn between one and two, my primary concern was what terminology to use here.

What about copy 1, with only a color (no text), slightly smaller, and no words (but instead a more descriptive voiceover) could be an idea?

**Comment by hedgefield** [comment]
Well, for a11y we'd need a second visual cue aside from color. I fear just a colored circle might be too vague. That's why I like 2, it's straightforward but because of the color it still feels special.

As for terminology, I was thinking:

- Poor
- OK
- Good

- Not great
- Fine
- Great

- Needs improvement
- Pretty good
- Great

**Comment by Clorith** [comment]
Yes, we would need a descriptive string then, if we're going with a color coded string I personally prefer copy 4, as it allows us to be a bit more descriptive in our text (like your third block of texts) without making the line feel too long.

**Comment by hedgefield** [comment]
Agreed. It could still use some finetuning, but it's a good starting direction. Shall we workshop this during WCEU contributor day?

**Comment by Clorith** [comment]
That sounds like a fantastic idea, let's make it so

**Comment by hedgefield** [comment]
While applying the new grading style to other mockup areas I found the verbiage to not work well in all contexts.

Consider if you're wondering how your site is doing, and you see FAIL. Oh okay, failed what? What does that mean? Is that bad? It still sort of indicates that there's a score underneath that you don't know about.

Maybe using `Can be improved/Good` is a better phrasing.

**Comment by Clorith** [comment]
Perhaps `Should be improved` instead of `Can be improved`? Since the `Good` state technically means there may still be room for improvement, while the "negative" side of it means there's critical things that the user should look to?

**Comment by Clorith** [comment]
OK, so what I've experimented and think is a good approach:

- Left critical issues weighted higher (didn't change them, this is just the way they've always been)
- Recommended issues are weighted lower, to indicate they are less pressing to give a better overall progression. This was done as I observed a few large plugins extending this section with recommendations which would sway the recommendations too heavily.
- Added a descriptive text informing that results are loading (to add clarification to the pulsing circle)
- Used the `Should be improved` text instead of `Could be improved`
- Regardless of what your grading becomes, if there's one or more critical issues, it _will_ show the `Should be improved` string, as critical things should always be addressed.

![new-grading](https://user-images.githubusercontent.com/468735/60290252-a7809f00-9918-11e9-90a7-8334b8653854.gif)

**Comment by Clorith** [comment]
I feel this ticket, and the version in `develop`, has sat long enough that we can close out this ticket as addressed.

We're aiming to get this release out some time in the coming week, so that we can get some input before pushing it for the 5.3 update of core.
