### ISSUE TITLE
Add filters to the Site Health tab section

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#344]
The Site Health tab navigation has 4 entries at this time (two in core), and there's already a core ticket asking for these to be filterable.

Filtering them has some side effects, there's a ticket for providing equal length navigation items, which relies on CSS grid and flex widths, and requires you to declare a fixed amount of columns. This will not work well with multiple navigation panels.

My initial thought is to add multiple column style definitions, based on a class, this will allow us to add a given amount of columns comfortably with equal widths.

This would be a temporary patch depending on how many entries there are, after this, we will need to consider adding a conditional dropdown navigation of sorts, to avoid overflowing the screen (especially as tabs do not look good when covering multiple lines), this would also make the navigation much cleaner on a mobile as we could compress all to the dropdown in those scenarios.

A concept like above was something I stumbled on some years ago, which dynamically nested things into the dropdown based on viewport width for the best possible experience, regardless of what device you were on, this is something worth exploring I suspect, as the device market is so diverse.

**Comment by ramiy** [comment]
Relevant Trac ticket to filter Site Health navigation tabs: https://core.trac.wordpress.org/ticket/47225

**Comment by Clorith** [comment]
Found a JSFiddle of what I was describing at https://jsfiddle.net/vadikom/tjbbvxz3/ which is part of a jQuery plugin called [SmartMenus](https://www.smartmenus.org). A solution similar to this might be interesting to pursue as it adjusts it self based on viewport and size.

**Comment by Clorith** [comment]
As this has been implemented in core with WordPress 5.8 (see the [relevant dev note](https://make.wordpress.org/core/2021/06/22/extending-the-site-health-interface-in-wordpress-5-8/) for details), I'm closing this issue in the plugin now.
