### ISSUE TITLE
Change required WP version due to wp_get_upload_dir function

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#353]
### Feature request/bug description

I tried the plugin on a website with WP 4.4 and got this error message:

> Fatal error: Call to undefined function wp_get_upload_dir() in /kunden/480922_73730/webseiten/newlife-figurzentrum.de/home/wp-content/plugins/health-check/includes/class-health-check-debug-data.php on line 49

`wp_get_upload_dir` is introduced in WP 4.5

See: https://developer.wordpress.org/reference/functions/wp_get_upload_dir/

So this needs to be updated to 4.5:
https://github.com/WordPress/health-check/blob/5c86c776a52c5f10064df1cc04445176ea8fcc7a/docs/plugin/readme.txt#L4

Or we add a check to disable this feature if we are on older versions.

**Comment by Zodiac1978** [comment]
I have digged a little bit more with https://wpseek.com/pluginfilecheck/

`wp_check_php_version` (since 5.1.0) has a fallback check:
https://github.com/WordPress/health-check/blob/a4cf9abbec5dd3f54554de6b8194886d854db7d6/src/includes/class-health-check-site-status.php#L724-L728

`wp_get_update_php_url` (since 5.1.0) has a fallback check:
https://github.com/WordPress/health-check/blob/a4cf9abbec5dd3f54554de6b8194886d854db7d6/src/includes/class-health-check-site-status.php#L747

`is_countable` (since 4.9.6) has no fallback check. For example:
https://github.com/WordPress/health-check/blob/a4cf9abbec5dd3f54554de6b8194886d854db7d6/src/assets/mu-plugin/health-check-troubleshooting-mode.php#L845

`get_user_count` (since 4.8.0) has no fallback:
https://github.com/WordPress/health-check/blob/5c86c776a52c5f10064df1cc04445176ea8fcc7a/src/includes/class-health-check-debug-data.php#L364

`get_user_locale` (since 4.7.0) has no fallback:
https://github.com/WordPress/health-check/blob/5c86c776a52c5f10064df1cc04445176ea8fcc7a/src/includes/class-health-check-debug-data.php#L85

So it seems to me that we should update to: `Requires at least: 4.9.6`

**Comment by Clorith** [comment]
Hmm, this may be changes ported back in from the WP core patches that I've missed when making back compat stuff... let's see which ones are reasonable to look at for back compat implementations.

Let's see if we can backport things to stay around the 4.7-mark on versions if possible.

`is_countable` is a PHP7 feature, which is put into core for back compat, so we can safely add that as a back compat in the plugin as well.

`get_user_count` is just a helper function for fetching a meta entry, so I think we can easily implement a fallback for this as well.

That leaves the remaining functions at the bottom of comment:2, the `rest_url` isn't a concern, as it's gated behind a check for the Rest API existing, ut the others are very useful tools that we'll want to be able to utilize, so makes sense to bump up to at least have access to these properly.

What version are we left with for a reasonable version increase then, is it 4.5.0, or am I missing others?

**Comment by Zodiac1978** [comment]
You didn't mention `get_user_locale` which would be 4.7.

The next one would be `wp_get_upload_dir` which requires 4.5, but maybe could be replaced with `wp_upload_dir` if not available.

See: 
https://developer.wordpress.org/reference/functions/wp_get_upload_dir/ and
https://developer.wordpress.org/reference/functions/wp_upload_dir/

This would get us to 4.3 which is required for `recurse_dirsize`
https://github.com/WordPress/health-check/blob/5c86c776a52c5f10064df1cc04445176ea8fcc7a/src/includes/class-health-check-debug-data.php#L1241

**Comment by Clorith** [comment]
I'm happy with 4.7 as a minimum, I think that saves us a lot of hassle, while still servicing the majority of users, and is a realistic expectation (-5 major releases), does this sound like a good approach to others?

**Comment by Zodiac1978** [comment]
In general I would agree, but in this case the tool is IMHO sometimes needed to help migrating from very old installs. But if this would be a major headache, let's tackle 4.7. :)

**Comment by Clorith** [comment]
You're right, this is a tool that's oh so handy in upgrade cases as well as general troubleshooting, so keeping with what we've already "promised" so to speak, seems fair to me for now.

I think this will align nicely with #347 when we get that far, but for now this new `compat.php` file should take care of the problems we currently face.
