### ISSUE TITLE
Incorrect database version reported when using MariaDB 10.4

### ISSUE THREAD

**Issue by dbrozi** [WordPress/health-check#358]
Installed MariaDB version 10.4.7 but Health Check shows version number as 5.5.5

Similar problem for Joomla reported here
https://github.com/joomla/joomla-cms/issues/9062

They report the following:
the mysqli.php driver function "getVersion" uses the "mysqli_get_server_info" rather than the SQL query "select version();"

Here is a screenshot from Health Check database
![image](https://user-images.githubusercontent.com/54535725/63687576-4dcd2000-c848-11e9-9583-0b5bdc1ec61b.png)

This is what running mysql -V shows
mysql  Ver 15.1 Distrib 10.4.7-MariaDB, for Linux (x86_64) using readline 5.1

This is what running the query select version(); shows
![image](https://user-images.githubusercontent.com/54535725/63687713-a69cb880-c848-11e9-90a1-d924290dd6fe.png)

**Comment by Clorith** [comment]
This was fixed in 2dc19733108b7e775006b2ceafd77116fb22c26d and will be included in the next plugin update, more information can be seen at https://core.trac.wordpress.org/ticket/47738
