### ISSUE TITLE
Add background update check

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#36]
Let's make this plugin the best support plugin and add some features.

How about adding the background update test feature?
https://de.wordpress.org/plugins/background-update-tester/

Or at least we could make this a one-click-install. There are some more plugins like Debug Bar  from the Core team which could be added here, too.

**Comment by Clorith** [comment]
Automatic udpate testing is already in (and is imported from that plugin), it's covered by the health check tab at https://github.com/WordPress/health-check/blob/master/pages/health-check.php#L355

Adding one-click installs is something I'd like to avoid, ideally users shouldn't need to install a lot of things to get the information they need, I feel like we've failed them a little if we direct them to get this plugin for -every- problem if it needs another tool to be sorted out. (that's my opinion though)

**Comment by Zodiac1978** [comment]
> Automatic udpate testing is already in

Sorry, I missed that. Great. :)

> Adding one-click installs is something I'd like to avoid

That was just an idea if the reason for not including it, was the existing plugin. I'm perfectly fine with including it and avoiding the red directing of the user to another plugin.
