### ISSUE TITLE
PHP Compatibility according to Tide

### ISSUE THREAD

**Issue by grappler** [WordPress/health-check#362]
### Feature request/bug description
According to Tide the plugin is only compatible till PHP 5.6: https://wptide.org/api/tide/v1/audit/wporg/plugin/health-check/1.4.0

Now that Tide results are being shown in the plugin it would be good to fix the cause of the incorrect information.

Related Issues: #53, #347

### Screenshots
![image](https://user-images.githubusercontent.com/1785641/65392354-598f0200-dd74-11e9-9df8-d0ff6bfcd941.png)

**Comment by Clorith** [comment]
The cause for the incorrect value is unfortunately the backwards compatible code allowing `mysql_*` functions, there's not much we can do to prevent this I don't think, it would have to be some kind of rule added on the side of Tide to somehow detect if it's back-compat code or not.

**Comment by grappler** [comment]
As Tide runs PHPCS. It is possible to add a PHPCS ignore comment.

**Comment by Clorith** [comment]
I was thinking about that, but the plugin already has the PHPCS ignore rules in, as I believe Tide intentionally do not "honor" the ignore comments to avoid bad plugins from trying to game it by ignoring things that are legitimate issues.

I did mention this in a Slack chat, I don't recall where, a month back, and they said they'd love to get some kind of rules to account for back-compat, but weren't aware of any at the time.
