### ISSUE TITLE
Mail Check should use "wp_mail_failed" action to provide better error diagnostics

### ISSUE THREAD

**Issue by siliconforks** [WordPress/health-check#364]
### Feature request/bug description

Currently if the Mail Check function fails to send an email, it always displays the generic error message "It seems there was a problem sending the e-mail."  It would be helpful to display the reason why the email failed.  In some cases no additional error information will be available, but when it is available, [WordPress will use the "wp_mail_failed" action](https://core.trac.wordpress.org/browser/tags/5.3/src/wp-includes/pluggable.php#L502) to provide a way to access this.

**Comment by Clorith** [comment]
Hmm, that requires WordPress 4.4 as a minimum (we're currently supporting back to 4.0) though.

I do absolutely agree that this is a good idea, so I'm going to add it to the next milestone, which would probably not be a bad time to consider raising the minimum WordPress requirement.
