### ISSUE TITLE
Add check of server time

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/health-check#367]
It would be useful to add check of server time.
1. Display current server time, both as default local server time and as UTC/GMT.
2. Compare server time against a few NNTP sources and flag if server time seems to deviate notably from current time.

**Comment by Clorith** [comment]
The Site Health checks and debug information have been taken out of the Health Check plugin as of version 1.5.0 (with some backwards compatible layers for sites running WordPress versions earlier than 5.2), and any new issues relating to these areas should be opened in the [WordPress core trac](https://core.trac.wordpress.org).

For this issue, there is a core ticket available at https://core.trac.wordpress.org/ticket/56378
