### ISSUE TITLE
WP 5.4 Site Health info doubled up on Dashboard page when plugin is activated

### ISSUE THREAD

**Issue by bph** [WordPress/health-check#369]
As the troubleshooting feature is not in the core version of the tool, I often install the plugin along-side WordPress. New to WordPress 5.4 is that the dashboard widget is now shown twice on the dashboard page. 

### Screenshots
![Screen Shot 2020-02-25 at 4 35 37 PM](https://user-images.githubusercontent.com/39980/75289713-e25f0d80-57ec-11ea-8c99-3c124d0d7564.png)

**Comment by Clorith** [comment]
This has been hotfixed prior to the release of 5.4 in the version on WordPress.org
