### ISSUE TITLE
Adding an integrity check / checksum verifier

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#37]
There are some plugins which provide such a check:
https://wordpress.org/plugins/look-see-security-scanner/
https://wordpress.org/plugins/checksum-verifier/
https://wordpress.org/plugins/integrity-checker/

In the forums there is often the question: **Is my site hacked?** This would be an easy first step to check.

**Comment by Clorith** [comment]
Maintaining a checksum verify list is a lot of work, as you need to store the sum of each file for each version. I think this is a task better served by dedicated plugins or services that have paid people to deal with keeping these up to date. I'd love to include an easy access link for this somewhere, but I'd also rather not show favoritism towards one plugin or another.

**Comment by Zodiac1978** [comment]
We don‘t need to maintain those checksums. There is an API for that, If I am correct.
https://codex.wordpress.org/WordPress.org_API#Checksum

**Comment by Clorith** [comment]
Intresting, I'd not seen that... Then this is certainly something that we could reliably implement, yes. It would of course not account for plugins or themes, but as a quick check it's something I'd likely expect to see 👍

**Comment by Zodiac1978** [comment]
I think there could be a way for plugins too, since WP CLI can do that. I think the meta Team helped Thema to accomplish that.
https://make.wordpress.org/cli/

**Comment by mrxkon** [comment]
This would be super nice! Should we give this a shot? At least for the core files first.

If yes @Clorith I was thinking of seeing if I could help on this (no idea though if we make PRs here etc ).

Just some extra thoughts and questions:

1. I was thinking for it to be on a separate tab i.e. **Files Integrity**
2. Output page: 
  a. Either output a nice simple list with ticks ( like the one on Health Check tab ) for each file 
  b. or even better just output if everything seems fine / list only with faulty checks.

If the case is 2b it could be implemented on any tab I guess.

**Comment by mrxkon** [comment]
Sorry for the extra mini-commits on the PR but I had some extra ideas of showing a useful ( i think ) reason of why the file is on the error list ( file not found / changed content ) and I had some minor edits as I was testing it on my live sites that I didn't realize when on local ^_^.

An extra thing for the future, maybe add a Diff view if the files have been changed so the user can easily see the differences and copy/paste if needed.

BUT! I would suggest to keep it on core files only, let's not go ahead and check all plugins / themes. There are already plugins more than capable of doing it and Health Check is already a beast as is imho let's not get everything else under it's shadow ( maybe? 😄 )

**Comment by mrxkon** [comment]
Adding this Comment as means of self-note and update to all that #35 will be implemented with this PR ( #41 ) as well probably by tonight even and under a single Tab named 'Tools' in Health Check.

**Comment by mrxkon** [comment]
The PR now has a Diff View as well. If the File Integrity check has files that are tampered there will be a ( Diff View ) link next to them.

The function cross-checks the local files with the core.svn by wp_remote_get() and shows a diff between them.

The gif preview is a bit 'slow' but I think it was a time when a migration was happening so the api and .org in general was a bit slow on responding at the time it was recorded it usually runs much faster to get results.

I hope you find this useful as well! 

![Preview](https://cldup.com/-D0K8gwbiP.gif)

**Comment by Clorith** [comment]
Introduced in 0d09bcb3a6fdecc11d1bb755710f2b2de61e56e0
