### ISSUE TITLE
Check for display_errors

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#370]
### Feature request

It would be great if we can also check if `display_errors` is enabled on the server as this is not recommended:
https://make.wordpress.org/core/handbook/testing/reporting-security-vulnerabilities/#why-are-there-path-disclosures-when-directly-loading-certain-files

Unfortunately there are many hoster (Siteground, 1and1/Ionos, Domainfactory, all-inkl.com, ...) with this setting enabled as default.

There are snippets flying around to add this to the .htaccess, but there are not working:

`<IfModule mod_php7.c>
    php_flag display_errors off
</IfModule>`

This is because if PHP is not running as a module but as FastCGI/PHP-FPM you need to use a `.user.ini` file with the content `display_errors = 0` instead or change this in your hoster settings.

**Comment by Ayesh** [comment]
I think this is a great idea, and if others express interest, I'd be happy to send a PR to this repo or to wordpress-develop repo. 

> There are snippets flying around to add this to the .htaccess, but there are not working:
> `<IfModule mod_php7.c> php_flag display_errors off </IfModule>`

They are quite fragile integration I would say. In PHP 8, for example, the [module name will be `mod_php`](https://php.watch/versions/8.0/mod_php-rename). There is nothing that prevents WordPress itself from hiding errors because the `display_errors` INI setting to 0 during bootstrapping though.

**Comment by Zodiac1978** [comment]
Related https://core.trac.wordpress.org/ticket/51806

**Comment by Zodiac1978** [comment]
@Clorith Is this the wrong place for such checks? Do I need to open a trac ticket instead? Is this the better approach?

**Comment by Clorith** [comment]
Hiya, sorry just been overwhelmed by trying to keep track of what is where with Health Check after Site Health was introduced to core.

New checks should be added as Trac tickets going forward, yes, if it doesn't fit the core scenario but the value is high enough, it can be implemented here in the plugin for those use cases specifically though.

**Comment by Clorith** [comment]
Closing as new, or modified, Site health Checks should now be created in WordPress core, and as such please make a ticket on the [Core Trac](https://core.trac.wordpress.org/)

**Comment by Zodiac1978** [comment]
Moved to: https://core.trac.wordpress.org/ticket/52652
