### ISSUE TITLE
wp.hooks missing from global variable, never finishes check

### ISSUE THREAD

**Issue by gmariani** [WordPress/health-check#371]
### Feature request/bug description

On many of my sites, the health test never finish, maybe 1/10 it actually completes. Below is the message I get in the console:

```
11:36:24.820 TypeError: wp.hooks is undefined site-health.min.js:2:3983
    t https://cressonaborough.com/wp-admin/js/site-health.min.js:2
    jQuery 4
```

I've attached a HAR file and a screenshot as well. There are no errors in the error log. Below is my list of plugins installed on the site:

Calendar | Version 1.3.14 by Kieran O'Shea
Clear Cache For Me | Version 1.3 by Webhead LLC
CryptX | Version 3.3.2 by Ralf Weber
CV Monitor | Version 2.6.1 by CourseVector
Disable Comments | Version 1.10.2 by Samir Shah
Google XML Sitemaps | Version 4.1.0 by Arne Brachhold
Offsprout Page Builder | Version 2.15 by Offsprout
Offsprout Pro | Version 1.5 by Offsprout
Simple History | Version 2.33.2 by Pär Thernström
W3 Total Cache | Version 0.13.1 by BoldGrid
Weather Atlas Widget | Version 1.2.1 by Yu Media Group d.o.o.
Wordfence Security | Version 7.4.6 by Wordfence
WPMU DEV Dashboard | Version 4.8.1 by WPMU DEV
WPMU DEV Videos | Version 1.7.3 by WPMU DEV

Was really hoping it would be fixed in WordPress 5.4, but after i saw it wasn't figured i'd open a ticket.

### Screenshots

![Screenshot 2020-04-01 11 37 08](https://user-images.githubusercontent.com/5058619/78156797-4472ea00-740d-11ea-99cf-becd0dc15024.png)

[cressonaborough.com_Archive [20-04-01 11-37-44].zip](https://github.com/WordPress/health-check/files/4416210/cressonaborough.com_Archive.20-04-01.11-37-44.zip)

**Comment by gmariani** [comment]
Still happening in WordPress 5.6

**Comment by gmariani** [comment]
Tracked down the issue to a plugin used to manage the Heartbeat feature in WordPress. It would call this:
`wp_deregister_script('heartbeat')`
to control when it was loaded. For some reason, de-registering the heartbeat script removes wp.hooks from the global variable and causes the error. Not sure if someone wants to add some check in site-health to verify that heartbeat is loaded.

**Comment by TimothyBJacobs** [comment]
@gmariani Does this only apply when using the Site Health plugin? If not I'd open a Core ticket. It looks like Site Health isn't specifying that `wp-hooks` is a dependency and relying on `heartbeat` to enqueue the library.

**Comment by gmariani** [comment]
@TimothyBJacobs Opening a core ticket. Thanks!
