### ISSUE TITLE
"Available Plugins / themes" tabs cannot be expanded in the Dashboard while in Troubleshooting Mode

### ISSUE THREAD

**Issue by rmarcano** [WordPress/health-check#372]
### Bug description

Using Health Check and Troubleshooting 1.4.3 and WordPress 5.4 breaks the "Available plugins" and "Available themes" tabs in the Dashboard when in Troubleshooting mode. 

The following Javascript errors are displayed in the console:
`Uncaught TypeError: Cannot read property 'site_health_complete_fail' of undefined`.

Steps to reproduce:
1. Make sure you are running WordPress version 5.4 and Health Check 1.4.3
2. Enable Troubleshooting mode.
3. Go to the "Dashboard", see errors in the browser console.
4. Try to expand the "Available plugins" accordion.

![js-error](https://user-images.githubusercontent.com/1044883/78168153-6e340d00-741d-11ea-81ac-57a5c1027724.png)

### Workaround
As a workaround, the "Available Plugins" and "Available Themes" tabs work in the Plugins section.

### Related issues:
https://github.com/WordPress/health-check/issues/373
https://github.com/WordPress/health-check/issues/374

**Comment by Clorith** [comment]
This was patched in plugin version 1.4.4, thank you for the heads up!
