### ISSUE TITLE
Javascript errors in "Info" tab while in Troubleshooting mode

### ISSUE THREAD

**Issue by rmarcano** [WordPress/health-check#374]
### Feature request/bug description
When in Troubleshooting mode, the following javascript errors are displayed in the browser console in the "Info" tab:

`Uncaught TypeError: Cannot read property 'site_health_complete_pass' of undefined`

Steps to reproduce:
1. Make sure you are running WordPress version 5.4 and Health Check 1.4.3
2. Enable Troubleshooting mode.
3. Go to Tools > Site Health > Info tab. See errors in the browser console.

### Software versions
WordPress version 5.4
Health Check version 1.4.3

### Screenshots
![info](https://user-images.githubusercontent.com/1044883/78170049-5ad67100-7420-11ea-81e8-008486dc596d.png)

### Related issues:
https://github.com/WordPress/health-check/issues/372
https://github.com/WordPress/health-check/issues/373

**Comment by Clorith** [comment]
This will self-resolve with the next release after f7d39936f96dc21c0daa3159596fcaaea5ced1b2 which removes this functionality from the plugin, as it is now bundled in WordPress it self, and the mix between the two was causing some confusion on what should be loaded when.
