### ISSUE TITLE
Question: what is the difference with the core health check?

### ISSUE THREAD

**Issue by mahnunchik** [WordPress/health-check#375]
### Question

What is the difference with the core health check? Is it the same plugin or not?

**Comment by Clorith** [comment]
Hiya,

There's two parts to this, there's the Site Health part of the plugin, which has the health check and debug information, which are part of core. New checks are tested in the plugin first to make sure they do what we want them to (think of the plugin as getting access to those tests early).

Then there's the second part, which is troubleshooting, these are tools that do not fit into the core project, as they are plugin territory and only used in very special circumstances, these are only available via the plugin (notably Troubleshooting Mode, and the Tools section of the plugin).

**Comment by mahnunchik** [comment]
@Clorith Thank you for the clarification. I think it should be mentioned in the description.

**Comment by Clorith** [comment]
That's a very good point, we should absolutely do that to avoid confusion!

Would you like to provide a patch for that? You can do so against the `develop` branch and the readme file at https://github.com/WordPress/health-check/tree/develop/docs

**Comment by mahnunchik** [comment]
I realized that a similar question is actual for Gutenberg plugin. So this information can be added to both plugin: users may chose to use prebuild version of plugins or install (replace) it with that plugins and use extended / unstable versions.

**Comment by mahnunchik** [comment]
I asked already the same question 8 month ago https://wordpress.org/support/topic/is-this-plugin-needed-with-wordpress-5-2/  😆 

So I think some documentation should be added to the readme of both plugins.

**Comment by Clorith** [comment]
I'm closing out this issue, as the features core and the plugin shared have now been fully merged entirely to core.

The Site Health checks and debug information have been taken out of the Health Check plugin as of version 1.5.0 (with some backwards compatible layers for sites running WordPress versions earlier than 5.2), and any new issues relating ot these areas should be opened in the [WordPress core trac](https://core.trac.wordpress.org).
