### ISSUE TITLE
Check for proloinged sending time for emails

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#376]
E-mails may some times hang during sending, we can test for this in the email testing tool.

Checking if a message is sent or not is fine, but it can be extended to include a warning if a message took longer than X seconds to be sent, which may indicate either that a system is overloaded, or there is a problem with the mailing service for whatever reason.

See also https://core.trac.wordpress.org/ticket/49815 for reference

**Comment by knutsp** [comment]
Has it also/ever been suggested or reviewed to include the E-mail check from the Health Check & Troubleshooting plugin in core?

**Comment by Clorith** [comment]
It hasn't, no, and I don't think that fits into core either, that's more a troubleshooting step and is plugin territory (it's also hard to do reliable e-mail testing, which I hope to tackle elsewhere to be perfectly honest)
