### ISSUE TITLE
Add a good hint on failed loopback test

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/health-check#377]
If a loopback test fails due to time out, then the answer in https://wordpress.org/support/topic/site-health-status-3/?view=all#post-12734967 suggests one possible cause for this problem that is not immediately obvious.
It would be good to add some verbiage in the test result about this:
"One possible reason for this error could be that your theme or some plugin uses session_start() for every call, since the loopback test in that case will be waiting for itself until the call times out."

**Comment by Clorith** [comment]
I'd like to avoid the technical aspect of mentioning specific functions in the user-facing response, the authors who may be responsible for the plugins or themes should be looking up this information instead I think?

**Comment by Clorith** [comment]
The Site Health checks and debug information have been taken out of the Health Check plugin as of version 1.5.0 (with some backwards compatible layers for sites running WordPress versions earlier than 5.2), and any new issues relating to these areas should be opened in the [WordPress core trac](https://core.trac.wordpress.org/).
