### ISSUE TITLE
Array to string conversion notice caused by plugin

### ISSUE THREAD

**Issue by pacmanito** [WordPress/health-check#378]
Hi. Each time I enter the plugin page 2 notices a thrown into my debug log:
`PHP Notice: Array to string conversion in ***\wp-content\plugins\health-check\includes\class-health-check-debug-data.php on line 1172`
`PHP Notice: Array to string conversion in ***\wp-includes\formatting.php on line 1115`
This happens even if all the plugins are deactivated.
Also another notice is thrown from time to time as well:
`PHP Notice:  Array to string conversion in ***\wp-content\plugins\health-check\includes\class-health-check-site-status.php on line 2014`
I was not able to trace what is triggering it, but it appears from time to time. Mostly when I visit my dashboard for the first time during the day.

**Comment by mbtools** [comment]
Same as https://github.com/WordPress/health-check/issues/384. close this and subscribe to the 384 :-)
