### ISSUE TITLE
Create an Exception for plain UTC timezone without manual offset

### ISSUE THREAD

**Issue by rolandog** [WordPress/health-check#380]
### Feature request/bug description

_Create an Exception for UTC without manual offset_

This would whitelist setting UTC (but not UTC+0) in order to not display a warning about 'manual offset' of time.

As I mentioned in the [WordPress support thread](https://wordpress.org/support/topic/your-site-is-not-using-localized-timeszones/#post-12655780), currently the 'Site Health' section displays a 'Performance' warning of 'Your site is not using localized timezones' if you set the timezone to UTC:

> Daylight Savings Time (DST) may affect the times used and shown by your site, and using an UTC offset, instead of a localized time zone, means that the site does not get automatic DST updates.

This is somewhat related to #317; this would help people (like myself) that believe that it would be more convenient to use UTC instead of time zones.

### Screenshots

![Screenshot from 2020-04-10 14-49-53 Cropped](https://user-images.githubusercontent.com/12400926/82146630-f21a4b00-984b-11ea-982e-3ce0f308ec3c.png)

![Screenshot from 2020-05-17 14-38-05](https://user-images.githubusercontent.com/12400926/82146646-0d855600-984c-11ea-8f31-dcd6827fd3b3.png)

Thanks in advance for your consideration!

**Comment by Clorith** [comment]
Hiya,

Thanks for this suggestions, I agree that having just `UTC` as the timezone might be a valid choice, I'll check in with the resident timelord and see if this is the right approach or not, but will milestone this for now, until it's been clarified one way or the other!

**Comment by rolandog** [comment]
No problem! Thank you for your consideration!

Oh, by the way, I forgot to mention that one of the reasons I was also filing this bug is that I didn't understand why this is labelled as 'Performance'; is it 'SEO Performance'? Perhaps it could be labelled as ['Internationalization'](https://www.w3.org/International/questions/qa-i18n)?

**Comment by Clorith** [comment]
The Site Health checks and debug information have been taken out of the Health Check plugin as of version 1.5.0 (with some backwards compatible layers for sites running WordPress versions earlier than 5.2), and any new issues relating to these areas should be opened in the [WordPress core trac](https://core.trac.wordpress.org/).

I'll note that the behavior here in core is that `UTC` by it self is valid :)
