### ISSUE TITLE
Be able to enable troubleshooting mode using a WP-CLI command

### ISSUE THREAD

**Issue by lukecav** [WordPress/health-check#385]
Something similar to this would be very useful.

`wp health-check troubleshooting`

**Comment by karudonaldson** [comment]
Seems unusual this module doesn't have CLI management.

**Comment by rickmgithub** [comment]
Please. It would have been useful in debugging today.

**Comment by Clorith** [comment]
Hmm, interesting idea, a bit cumbersome to administrate, and would only affect the CLI instance, as well as require a start and stop sub-function (since you can't tie it to a session, like we do in the browser).

All of that said, yeah I can definitely see a use for this.

**Comment by Lucisu** [comment]
It could have the parameter "--user" and tie the troubleshooting flag to the user meta.

I'm available to do this if wanted.

**Comment by Clorith** [comment]
Looking (and thinking) more on this recently, and I'm not sure if a troubleshooting mode support for WP-CLI makes sense a this time.

The WP-CLI instance has global parameters for `--skip-plugins[=<plugins>]` and `--skip-themes[=<themes>]`, which basically let you run individual commands or instances without any plugins, themes, or specific plugins or themes. This is in theory what troubleshooting mode does within a browser instance as well, so trying to "re-invent the wheel" here, as it were, seems counter productive unfortunately.

Based on this, I'm closing the ticket for now, but if good use cases should appear, the ticket can of course be re-opened at such a time :)
