### ISSUE TITLE
i18n standards: use _n() instead of__()

### ISSUE THREAD

**Issue by vlad-timotei** [WordPress/health-check#400]
### Issue description

These lines should use _n() instead of __()

- https://github.com/WordPress/health-check/blob/trunk/src/php/assets/mu-plugin/health-check-troubleshooting-mode.php#L1092

- https://github.com/WordPress/health-check/blob/trunk/src/php/assets/mu-plugin/health-check-troubleshooting-mode.php#L1171

### Reasons
- There are languages that have different plurals 
- There are cases where exactly 6 themes and 6 plugins are installed ( 6-5=1 ), resulting in the following incorrect outputs: 
_Show 1 remaining plugin**s** / Show 1 remaining theme**s**_ 

### Screenshot

![image](https://user-images.githubusercontent.com/65488419/114355838-9c901080-9b78-11eb-9407-928f6d51fa5d.png)

Polyglots team confirmed this [here](https://wordpress.slack.com/archives/C02RP50LK/p1618162291480500)

**Comment by vlad-timotei** [comment]
The same issue is here: https://plugins.trac.wordpress.org/browser/health-check/tags/1.4.5/includes/class-health-check-dashboard-widget.php#L91

Result:
![image](https://user-images.githubusercontent.com/65488419/114430188-dc7de480-9bc6-11eb-816a-f273c96f9a6f.png)

**Comment by Clorith** [comment]
The Site Health checks and debug information have been taken out of the Health Check plugin as of version 1.5.0 (with some backwards compatible layers for sites running WordPress versions earlier than 5.2), and any new issues relating to these areas should be opened in the [WordPress core trac](https://core.trac.wordpress.org/).

Making note that the original issue was committed in #402, and that the dashboard widget is now handled by core :)
