### ISSUE TITLE
Disambiguation: 'the websites server user'

### ISSUE THREAD

**Issue by vlad-timotei** [WordPress/health-check#403]
https://plugins.trac.wordpress.org/browser/health-check/tags/1.4.5/includes/class-health-check-debug-data.php#L617

If unknown server user, the output message is _Unable to determine the **websites server user**_ -  that is pretty hard to translate without any context. Some translators assumed it's a typo and translated with: Unable to determine the **website's** server user. If it is indeed a typo, then the label should have the same format. 

Currently, the label is _Website server user_, so the description should be similar: _Unable to determine the website server user_ although it's easier to understand in this form: _Website's server user_ /  _Unable to determine the website's server user._ 

Either way, these two should be consistent.

**Comment by Clorith** [comment]
The Site Health checks and debug information have been taken out of the Health Check plugin as of version 1.5.0 (with some backwards compatible layers for sites running WordPress versions earlier than 5.2), and any new issues relating to these areas should be opened in the [WordPress core trac](https://core.trac.wordpress.org/).
