### ISSUE TITLE
Difference between core and plugin

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#421]
### Feature request/bug description

Looking at the database info in WordPress 5.9 core shows me 11 entries.

After installing the plugin (assuming this _adds_ more info/features) it only shows 7 entries.

For example there are added two lines with https://core.trac.wordpress.org/ticket/53845

Maybe there are more differences between core and plugin and I think users do not expect to have _less_ features after installing the plugin.

**Comment by Clorith** [comment]
You are absolutely correct, unfortunately I've been struggling to keep up with maintaining the plugin and core side by side, as core moves faster.

I'm working on resolving this though, using core for the data, and having older WP installs display a back-compat page with a warning, as you say, it should be expected that the plugin provides more, not less.

**Comment by Clorith** [comment]
With the release of 1.5.0, WordPress core is now used for the site health checks, and debug data. A backwards compatibility layer for WP versions earlier than 5.2.0 has been left in, but will intentionally not be receiving any updates, as it is just left as a courtesy for now.
