### ISSUE TITLE
Disable Troubleshooting Mode gives 404 as wrong URl.

### ISSUE THREAD

**Issue by ipajen** [WordPress/health-check#445]
### Description
Disable Troubleshooting Mode gives 404 as wrong URl.

/blog/blog/wp-admin/?health-check-disable-troubleshooting=1&_wpnonce=fcce9b632a)

there is one to much /blog/ in the URL, same issue on to enable available plugins.

### Environment
- WordPress: 6.2.1-alpha-55611
- PHP: 8.2.3
- Server: LiteSpeed
- Database: mysqli (Server: 10.4.28-MariaDB / Client: mysqlnd 8.2.3)
- Browser: Safari 16.4 (Mobile) (iPhone)
- Theme: Twenty Twenty-One 1.8
- MU-Plugins: 
  * Health Check Troubleshooting Mode 1.9.0
  * WordPress automation by Installatron 
- Plugins: 
  * Enable jQuery Migrate Helper 1.3.0
  * Health Check & Troubleshooting 1.6.0
  * WordPress Beta Tester 3.3.7
  * WP SMS 6.1.3

**Comment by Clorith** [comment]
Could you share your site setup, is this a single or multisite, and is it installed within a subdirectory?

**Comment by ipajen** [comment]
Single site with Subdirectory.
