### ISSUE TITLE
Suggestion: remind user to backup before troubleshooting

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/health-check#45]
As we have seen in the reviews for this plugin, now and then unexpected things happen in troubleshooting mode.
Could we add the following information on the screen with the button "Enable troubleshooting mode":

Due to the way the troubleshooting mode functions, and unforeseen clashes with other plugins, it may in rare cases happen that the use of troubleshooting mode leads to changes in your database and/or files.
We therefore strongly recommend that you make sure that you’ve saved a backup of your database before you enter troubleshooting mode. (Link to instructions?)
Additionally, since we really want to make this plugin as safe as possible, if you should have any problems with the troubleshooting mode, please create a new topic in the /link/plugins support forum/link/ with details about what theme and what plugins you’re using and the steps needed to reproduce the problem. This will help us to analyze and fix such problems.

**Comment by Clorith** [comment]
Hmm, I was actually sort of thinking about cutting down the text and removing the checkbox, as you can jump into TS mode directly from the plugins screen as well these days, it doesn't make much sense wit hall the warnings any more (they were originally there to make sure users knew how to leave TS mode).

But I like the way you are thinking, perhaps a confirmation box with the backup warning is in order as the solution here?

**Comment by tobifjellner** [comment]
Adding too many loops before you can reach that troubleshooting mode isn't good neither.
And my host saves regular backups automatically. I'd go mad if I had to confirm every time.
If you make such a confirmation box, make sure that you also have a second tick box. "Got it. No need to remind me about this again, ever..." :)

**Comment by Clorith** [comment]
Yup, one time warning kind of deal, like we do on the theme/plugin editors, makes the most sense in my mind at least (also lets me make it a prettier box than just a javascript alert box, those are so dull 😆 )
