### ISSUE TITLE
Feature Reqeust: Add GitHub Plugin URI

### ISSUE THREAD

**Issue by ipajen** [WordPress/health-check#450]
### Feature request
If the GitHub Plugin URI would be added on the health-check plugin it would be so easy to download the latest GitHub version of health-check with https://github.com/afragen/git-updater to test for example a bug fix.

Thank you!

**Comment by Clorith** [comment]
Thank you for the suggestion. Unfortunately, there are no plans to introduce non-standard plugins headers, or to change the plugins deployment flow in such a way as to be compatible with the GitHub Updater plugin at this time.

You are of course welcome to manually reference the GitHub repository from the GitHub Updater interface if you so wish, but note that no built assets are part of the repository, so styling and JavaScript files will be missing from your instance in those cases, which may lead to unexpected behavior or broken visuals.
