### ISSUE TITLE
Check if a non-virtual robots.txt file exists and show the content

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#454]
### Feature request

First reported here: https://core.trac.wordpress.org/ticket/56595

> For high traffic sites, it would be better to have a non-virtual robots.txt file, to prevent PHP/WordPress handling this.
> 
> But if we create a robots.txt file it is easily missed that now WordPress is not handling it anymore.
> 
> Therefore I suggest adding a check to Site Health if there is non-virtual robots.txt file in the root directory.
> 
> Maybe we could also add the content of this file in the info area and/or in the tools section of the plugin.

This could be added as a tool, like the .htaccess viewer and therefore it is better suited for the plugin, than core. Although I hink it should be reported like the changed .htaccess in the info tab.

**Comment by Clorith** [comment]
Added in [015347b](https://github.com/WordPress/health-check/commit/015347bc7cf1b5fb81281add0a7db5d4f7b5de66)
