### ISSUE TITLE
Feature request/bug - Minimum PHP for Health Check & Troubleshooting

### ISSUE THREAD

**Issue by ipajen** [WordPress/health-check#468]
### Feature request/bug description

compatibly - Minimum PHP. 
The minimum PHP version of Health Check & Troubleshooting is not shown "-"
In the readme.txt I find Requires PHP: 5.6 but in the health-check.php no version is defined. (Many plugins seems to have the information in readme.txt, could Health Check & Troubleshooting check here also)?

With the WordPress 6.3 and drop of 5.x support of PHP, maybe its time to bump minimum version of PHP for Health Check & Troubleshooting?

### Screenshots

Is this a visual related ticket? If so, please include one or more screenshots to help us better understand what is happening.

**Comment by Clorith** [comment]
As the Health Check plugin supports WordPress versions down to version 4.4, it will currently not have it's minimum PHP version raised, other than that, we'll add the readme headers to the primary plugin file as well :)
