### ISSUE TITLE
Add "test real memory limit" to tool tab

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/health-check#50]
Sometimes due to the configuration at the hoster level the settings value does not reveal the real memory limit. We could add another tool to test the real memory limit.

This example tries to allocate the memory and breaks at the end, so we know the real limit. This have to be more comfortable, but could be a start:
https://schnurpsel.de/wp-content/uploads/2009/12/memory-test.zip

**Comment by mrxkon** [comment]
I'm not sure if I have understood correctly the outcome of this test, but the code you attached was throwing some errors as it couldn't read the memory correctly, I re-wrote it and fixed those on my local tests. See -> [class-get-memory-info.zip](https://github.com/WordPress/health-check/files/1751627/class-get-memory-info.zip)

What this does though is actually stacking up the memory also as well. To give an example on every run =
`Memory Usage: 535105344 (510.32M) Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes)`
`Memory Usage: 799880624 (762.83M) Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 8192 bytes)`

And the actual Memory usage keeps stacking up until you have a full memory and crash the server.

I don't see why should add something like this if it's something that actually 'breaks' things to get the info wanted. Sorry if I'm missing something here or failing to understand the actual purpose.

**Comment by Zodiac1978** [comment]
The problem is, that some hosters hard limit the memory limit (1and1 did that in the past). If you use the obvious way to get the memory limit it responds with a false value. If you set a bigger memory limit, this bigger value is reported back (but still hard limit much before).

So the purpose of the tool would be to get the real memory limit in this case. Of course the error handling should be handled invisible and just output the correct limit.

Does this make more sense to you now?

**Comment by mrxkon** [comment]
Yeap, it makes total sense and thank you for clearing it up.

My concern still stays though as 'what if there's no hard limit to cap' ? There are localhost installs & dedicated server that don't have hard limits etc that we have to consider as well.

For example if I run this script on my local I will end up with my Windows freezing up from being out of memory. I just fear that it will cause more issues than make good as it could be easily abused without even knowing it.

**Comment by Clorith** [comment]
I'm also a bit concerned here, as there are many potential pitfalls to effectively trying to "break" the memory limit in such a manner. I do see the merits as well, but knowing the target audience, this is more likely a bad idea than not I'm afraid.

**Comment by Zodiac1978** [comment]
I'm fine with closing. It was a big problem with the hoster 1and1 for some time. But this is now solved. So we can close this here :)
