### ISSUE TITLE
exclussions on diff

### ISSUE THREAD

**Issue by mrxkon** [WordPress/health-check#56]
yui mentioned on slack: `and it shows modified files - readme.html version.php and wp-config-sample.php , because of localized version`

Maybe re-consider of excluding these 3 as well with `wp-content/` as I had it on the first version of checks?

**Comment by Zodiac1978** [comment]
There are some more, see this thread for another checksum verifier plugin:
https://github.com/pluginkollektiv/checksum-verifier/issues/4

**Comment by mrxkon** [comment]
I'll close this as it was merged already. @Clorith informed me that we shouldn't exclude anything. It's better to show what has actually changed, even if it's just from translations. This ticket was meant to close as well with the merge ^_^.
