### ISSUE TITLE
Maybe: tools page split design

### ISSUE THREAD

**Issue by mrxkon** [WordPress/health-check#62]
What do you think of this? I feel like the full width `notice` tools could just split up so they feel more like `tool sections` instead of actual notices.
![tools-split-design](https://user-images.githubusercontent.com/22611066/36556696-c0de35d4-180e-11e8-9b20-1a93bb4d7240.png)

**Comment by Clorith** [comment]
Why not some kind of accordion view, that would also let us group the results to the "area" they belong with? (you'd still be using the full width, but it would feel a bit more organized if we add more tools)

**Comment by mrxkon** [comment]
We could utilize the way Widgets open/close I guess sure. I was just trying to avoid 'extra clicks' and scroll. I'll get it done so we can see how it feels 'live'.

**Comment by mrxkon** [comment]
Leaving it here as a reply so more people can take a look in case there's anything extra to be done or some thoughts maybe ^_^

![New Tools Design](https://cldup.com/vaJyez91l7.gif)
