### ISSUE TITLE
Proposal: debug.log viewer

### ISSUE THREAD

**Issue by mrxkon** [WordPress/health-check#63]
I'm already running Health Check on all of my installations, it's one of the 'install as soon as WordPress is installed' plugins on my list and usually the next thing I bump in is a plugin that I wrote to be able to see the debug.log without editing `wp-config.php` etc.

It seemed easier for me to have a debugger within my admin pages just for development work ( I'm using `error_log()` for pretty much everything when I code.

For some time now I see on forums requests to enable debugging and then report back or simply check if anything goes wrong in there and usually it's with installations that are not getting white screens on their admin side so it would be handy to have it in there for the ease of access.

It's a straight forward thing, just a textarea that outputs everything.

What do you think? Could it be worth it implementing something like this to:
1] avoid long explanations of how to enable debugging.
2] help a user if he doesn't have access for any reason
3] help any developer that might think like myself of having a viewer handy always.

![WP Live Debug](https://raw.githubusercontent.com/mrxkon/wp-live-debug/master/assets/screenshot-1.png)

**Comment by Clorith** [comment]
I have a few concerns regarding this.

Firstly, to enable debugging your `wp-config.php` file needs to be edited, I'd rather a user do the editing than us try to programatically change this file (processes can hang for example, which would cause headaches). It's then better that the user knows how to edit this file if they are going to need to fix it manually, and it saves us a potential failure point.

The debug logfile can in some cases contain sensitive information, plugins or themes might check for `WP_DEBUG` and put in things like API keys or similar, or just paths to simple things like a backup file. Making the creation of this file easier on the user, and then it's a "set and forget" where they leave the file filling up over time with lots of information anyone can access by just going to the default location isn't something I feel comfortable with.
To negate this second point, we would have to delete the file for them, *and* disable `WP_DEBUG`, which brings us back around to problem 1.

I suspect this is the kind of thing where educating users via the plugin won't be as effective as we would like, they would leave it running, where as if they have to manually do the work, it's their own responsibility.

**Comment by mrxkon** [comment]
Let me try and counter everything in order :) . I see your points but consider that:

I'm not even editing the `wp-config.php` file even with my plugin, I would never do that either way. The idea on how it's enabled / disabled is this:

```
ini_set( 'error_reporting', E_ALL );
ini_set( 'log_errors', 1 );
ini_set( 'display_errors', 0 );
ini_set( 'error_log', WP_CONTENT_DIR . '/debug.log' );
```

As soon as you enter the debug viewer the log_errors starts to work, and as soon as you exit ( or disable the plugin ) it stops and based on your theory that is correct I might as well make it clear the contents before exit even to keep it light ( good point that I didn't think ).

As for the sensitive information I don't see a difference a user enabling it on his own or enabling it by a plugin ( there are already many plugins out there on the directory that do the same ). The information would be the same either way.

If you have admin access you could enable and view the log even from the Plugin Editor so a malicious user could either way do anything. And that's the owners fault.

As I see it 'health check' is to be used only by the Administrator or Dev of any page that has problems not from Editors or any other user that has lower permissions, that's why I thought that it wouldn't be a problem since you already 'own' the site :).

**Comment by Clorith** [comment]
I'll definitely like to leave it open for input from others, as we've got two opposite views it would be great to let it sit and wait for input from others :+1: I do like the influx of new ideas though!

**Comment by Clorith** [comment]
Just some more thoughts I've had over the last few weeks on the issue.

We could consider this, the main issue is the `wp-config.php` file to enable the debug flags, I feel that I could safely make automated modifications here, but we should take precautions, create a backup of the original file first, sandbox it and test for a broken site and revert.

Modify the `.htaccess` file, we want to block access to `debug.log` from the outside for safety reasons, make it only accessible either via a file editor, FTP (or similar direct access), or via a plugin.

Once done, truncate `debug.log`, remove the `.htaccess` rule and revert the `wp-config.php` (clean up after our selves).

I'm starting to think we can do this.

**Comment by mrxkon** [comment]
Just in case I could save you some time ( if it even goes near on what you where thinking ).

https://github.com/mrxkon/health-check/compare/master...mrxkon:enable-wp-debug

This link will easily compare the changes.

I've created 2 methods for enabling ( creating a backup + adding the debug constants ) + disabling ( restoring the backup / todo: if backup doesnt exist remove the constants to disable wp_debug ).

I'll probably play more with this within the next days but feel free to either pause me or throw any insights for a better management of things just in case I can tackle everything in 1 go.

**Comment by mrxkon** [comment]
Updating ( means of notes as well ):

The branch is almost complete 'debug' wise:

* If `WP_DEBUG` is enabled it will automatically open this tool to show the debug log ( I'll probably convert this to a native Health Check option to read instead of the constant as people might have already debug enabled etc )
* `enable` creates a backup and a temp file, parses the temp file to find all relative debuging constants and replace them with what we need, puts the end result into wp-config.php
* `disable` replaces the edited wp-config with the backed up one ( I have to add some checks if debug was enabled before us to disabled it ( maybe? ) )
* New tool 'Live WP Debug' has been added
* You can select to enable / disable the live debug.log view
* You can select to start / stop the auto refresh ( 3s intervals at the moment )
* You can select to fully clear the debug.log

**Comment by mrxkon** [comment]
OK! @Clorith I'm in somewhat of a mind-block at the moment as I can't think of anything else. So a review / extra input on the PR when possible would be a bless to see if I can do anything else before passing it over for sandbox stuff etc.

The only thing I could think of was to actually inform the user of what is enabled/disabled (wp_debug, wp_debug_log, display_errors) and give him the options to change anything. But I've put me on a halt to wait for a bit of input first 😄 .

**Comment by mrxkon** [comment]
**Question**:

I do display all 'debug' options if they are enabled/disabled, but I haven't add an on/off for `SCRIPT_DEBUG` and `SAVEQUERIES` tell me if you want them though for more 'advanced' users.

**Updates on the latest commits**:

I did a re-write of the whole flow. If you don't create a backup then you can't change any of the options ( debug, debug_log, debug_display ). There's a separate button now to restore your backup. I will add a function as well later today on plugin deactivation as well to restore + clean the backup so if they remove the plugin we end up clean again and I `think` it's ready :].

--

I think that if we add your 'sandbox' way on this after I'm finished it's going to be pretty much bulletproof.

**Comment by Clorith** [comment]
I'm moving this off the 1.2.0 milestone for now, we need to make more considerations before this feels right.

Just showing them the content of the file seems like a good idea, but does it really provide -that- much benefits to users?

Ideally I would have liked the user to be able to enable/disable debugging via the plugin for this to go in, but some poking tells me many hosts lock down the `wp-config.php` file, requiring direct access to make changes to it. This means users would need to do manual code edits to get access to features.

How do we move forward here, what thoughts exist around it?

I'd like us to consider if it's really that useful for users to be able to see the content of a file they'd be able to access directly if they knew how to enable the mode in the first place. This because I'm not happy with adding a feature only some users can use, but is locked away for others, that's a bad user experience in my opinion.

**Comment by Zodiac1978** [comment]
It looks like an easy first step could be to leave the updating of the `wp-config.php` to the experienced user and just display this tool of there is a `debug.log` available.

This plugin seems to be the same:
https://wordpress.org/plugins/error-log-monitor/
