### ISSUE TITLE
Enable English language in tab page=health-check&tab=debug

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/health-check#7]
It would be good to offer an untranslated version of the tab debug, that may be used to copy/paste the information to an international forum.

**Comment by Clorith** [comment]
I do see the value of this, although I'm wondering about implementation, there are various ways this can be handled (the simplest of course being just using Google Translate if you get a debug display that's not in English);

**Add original strings to each line**
![image](https://user-images.githubusercontent.com/468735/31577438-ad98cd5c-b10e-11e7-8a88-2979ce8179fd.png)
This approach is obviously rather messy

**Add extra copy-box**
![image](https://user-images.githubusercontent.com/468735/31577446-f077b61a-b10e-11e7-97ce-0dd8372f10fa.png)
Obviously cleaner, but does require all labels etc. to be added twice, which adds complexity, we'd need a fallback if someone didn't add the 2nd field which means we'd end up with translated text in the "English only" section (this is really just me thinking bigger picture if someone extends the debug data at any point).

**Comment by tobifjellner** [comment]
I like the Add extra copy-box approach. Is there any nice and neat way to reuse same code twice?
Say by creating a class that takes the desired locale as an argument?

**Comment by Clorith** [comment]
Hmmm, yes with WordPress 4.7.0 we have `switch_to_locale()` as an option, for previous versions we would have to use `load_plugin_textdomain()` which is a rather expensive function to run, it _might_ be OK to use in such a limited scenario as this is, but it isn't ideal of course. I think it's worth checking what the performance is like in any case 👍

**Comment by Clorith** [comment]
I think, for now, adding bi-lingual support in here for 4.7 and up is an OK approach, ideally we want users to be staying up to date with their core versions after all.

If, by some weird coincidence, we see a need for it for older releases, we can revisit the topic at such a time.

**Comment by tobifjellner** [comment]
I think this is fully ok. Especially since one of our favorite first remedies is "Have you updated core, your theme and plugins to the latest version?" :)
