### ISSUE TITLE
Close file diff view with <esc> key

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/health-check#76]
When the “file diff” modal is shown (Tools-Check the Files integrity-View Diff): Listen for keys and close the modal if <esc> is pressed.

**Comment by Clorith** [comment]
Makes sense,  we should do that for improved a11y as well 👍

**Comment by mrxkon** [comment]
I can 'add' this on the PR of the tools redesign if you like since it's on the same part of Health Check as everything is changing in there already 😄

**Comment by Clorith** [comment]
Please do, @mrxkon 👍

**Comment by Clorith** [comment]
This is in source, will be included with the next release.
