### ISSUE TITLE
Proposal: Total size of installation

### ISSUE THREAD

**Issue by mrxkon** [WordPress/health-check#81]
I saw a post on the Health Check support forums asking if there was a possibility to add a database size. I don't find it a bad idea to be honest and I was thinking of adding more stuff on top of that even.

Maybe an extra 'tool' that could show the current database + installation size in general?

For example:

Total size: 100mb
--
Database: 5mb
Plugins: 20mb
Core: 30mb
Uploads: 45mb

or something like that so users could easily see how much space does their installation take on a server? In my case as I'm managing various sites / instances it would be easier to just check the admin page at any given site than going through CPanels WHM every time on each account :) that's why the whole concept of this came on my mind.

**Comment by Clorith** [comment]
I like it 👍 

You may want to grab some inspiration form how I scan through directories in the string locator plugin (doing it chunked) to avoid timeouts and other fatal errors, as this could easily become a slow process on many instances.

**Comment by mrxkon** [comment]
Thanks @Zodiac1978 I already have something ready on my fork that reads WordPress (full dir) / Themes / Plugins / Uploads / Database sizes, but I'm struggling with the iteration ( chunks ) that Clorith mentions.

All plugins are just pulling everything in a single loop as I did as well. I'll probably just throw the PR here so we can have a chat over the chunks if I don't come up with something.

**Comment by mrxkon** [comment]
I've tried various ways of going through the folders just in case of a `timeout` but my `issue` let's say is this:

If I want to go through folders in batches I still have to get a full list at the start to split it up ( at least that's how my brain thinks ) so: If I'm to get a list first then imho there's no point of going back and forth after to get the sizes as getting them straight away is pretty much the same thing and even quicker.

Now I'm not familiar with `DirectoryIterator` if that would be a way to go, but this did run on various shared hosts ( good thing that I have plenty of sites to test on :P ) going from 2k up to 80k files without causing me timeouts ( there's no special setup for timeouts on those hosts btw ), and if it does I guess it would just not return anything still, you wouldn't end up with an error screen.

In any case here's a little screen to avoid patching to see how it looks at least.

More thoughts and scribbles are always welcome since I'm about to learn new stuff from this PR for sure :D 

![xk20180319072639](https://user-images.githubusercontent.com/22611066/37579650-21521e48-2b48-11e8-9c42-da9d82d70809.jpg)
