### ISSUE TITLE
Proposal: Description on PHP Libraries and update notices

### ISSUE THREAD

**Issue by apermo** [WordPress/health-check#90]
I stumbled upon a question on a WordPress support group. Where a normal Wordpress user used this plugin and asked:

Hey my cURL is outdated, what is it and how can I update it. 

I think it should be considered to add a short notice for these non techs what it is, that it’s only something to concern if you’re running your own server. And that you could only ask the hosting company for help here. 

Maybe it’s even possible to check vs a database if the php libraries used are only outdated or if a version has known vulnerabilities

**Comment by tobifjellner** [comment]
A more generic approach would be to include a few words about PHP libraries, that they are a part of the installation environment and there are maintained by the person/entity who runs the server + links where one could find more information about these libraries and check what version is the latest...
The good thing about such approach:
- Less work for translators
- Won't create additional external traffic
- After all: Why spend too much effort on something that isn't really actionable by the majority of users?

**Comment by apermo** [comment]
I think that solves the problem. The ordinary user won’t bother what cURL exactly does. He just needs to know that he can’t do the upgrade on his own.

**Comment by Clorith** [comment]
This is currently what shows up, I've included two cutoff points, one for the lowest version we know works (currently 7.38), and the latest stable version (currently set as 7.58, but I know 7.59 was recently released).

![image](https://user-images.githubusercontent.com/468735/39668234-417e425a-50c8-11e8-8b60-99ee1e49a877.png)
The message above shows up if your version is greater than, or equal to, the latest tested version. It's highly unlikely that a host will ever be fully up to date on the cURL front though, so I'm very open to ideas for how we can improve this area. It's definitely an aspect of your hosting setup that will affect any external communication with 3rd party services.

**Comment by Clorith** [comment]
After some consideration, removing this from the health check first tab, and only showing the version in the debug tab makes sense.

The extra text doesn't mean much to end users, and if you're looking into a connectivity issue for a user you'll know to ask for the cURL version or to look for it in the debug information posted.
