### ISSUE TITLE
Check for TLS 1.2

### ISSUE THREAD

**Issue by Shelob9** [WordPress/health-check#92]
### Feature request/bug description

A common problem I run into doing support for my plugin is TLS 1.2 is not being used or is not configured correctly.

I normally recommend https://wordpress.org/plugins/tls-1-2-compatibility-test/

It would be really cool if this plugin had that built in. The two things I'd like to have checked:

- Is TLS 1.2 active? Red flag if not
- Can WordPress HTTP API send an SSL encrypted message to an HTTPS server correctly?

**Comment by Clorith** [comment]
We're already performing the HTTPS connection tests, we're not performing TLS tests though, I can see that as useful, but I'd like to avoid pinging external services (the plugin you mentioned pings PayPal to test), we should be able to handle this without that need for this to be viable.

**Comment by Clorith** [comment]
I'm going to close out this issue, as it's not one we come across enough that the existing plugin(s) don't already provide the assistance needed.
