### ISSUE TITLE
Bulk action for plugins

### ISSUE THREAD

**Issue by Clorith** [WordPress/health-check#99]
If you suspect a small portion of plugins are the root cause, and you wish to test this, it becomes tedious having to enable one at a time.

We should introduce a bulk action for enabling or disabling plugins during troubleshooting to make this process less painful.

**Comment by Clorith** [comment]
When implementing this, as we're already working on manipulations on the plugins screen, let's also do the following to improve the user experience and avoid confusion/accidents:

- Add a plugin row link to get to the health check page
- Remove "Troubleshoot" fro the actions of individual plugins, instead leave it purely as a bulk action. This avoids accidental clicks, or clicking it without realizing what it truly does.
- When bulk-actions are applied, let's add an admin notice saying what they've done (the text from the Troubleshooting Mode tab might be useful to replicate here).

**Comment by jocastaneda** [comment]
Sort of a simplified version of the plugins screen?

What tab were you thinking?

**Comment by Clorith** [comment]
I was thinking of extending the plugins screen, as this is where users would expect to manage plugins in the first place and feels natural.

The scenarios I'm thinking should be covered are:

__Not in TroubleShooting Mode__
Add `Troubleshoot plugins` to the bulk action dropdown, make sure that if they are bulk-performing this action we only add activated plugins, and skip any in-active ones they may have chosen (to align with the rest of the plugin not supporting in-active plugins).

__In Troubleshooting Mode__
Bulk action options are removed from in-active plugins altogether.

The bulk-action dropdown menu only has two options: `Enable while Troubleshooting` and `Disable while Troubleshooting`.

Does that sound like a reasonable approach?

**Comment by jocastaneda** [comment]
I kind of see what you're saying.

**Comment by Clorith** [comment]
Implemented in 036c70963d95ef28e3439af1bfd06818afd41ef2
